import {
  Smartphone,
  ShieldCheck,
  MapPin,
  Building2,
  FileCheck2,
  FileText,
  UserCheck,
  CreditCard,
  Award,
  FolderCheck,
  CheckCircle,
  FileBadge,
  Building,
} from 'lucide-react';

export const buyerVerificationConfig = {
  INDIVIDUAL: {
    buyerType: 'INDIVIDUAL',
    portalTitle: 'Individual Buyer Verification Portal',
    pageTitle: 'Personal Identity & Mobile Verification',
    badgeText: '✓ VERIFIED BUYER',
    incompleteBadgeText: 'Verification Pending',
    totalRequired: 3,
    steps: [
      {
        id: 1,
        key: 'mobile',
        shortLabel: 'Mobile',
        name: 'Mobile Verification',
        req: true,
        icon: Smartphone,
        description: 'Verify your registered mobile number using secure one-time password (OTP).',
      },
      {
        id: 2,
        key: 'identity',
        shortLabel: 'Identity',
        name: 'Identity Verification',
        req: true,
        icon: ShieldCheck,
        description: 'Verify your identity securely using authorized verification protocol.',
      },
      {
        id: 3,
        key: 'address',
        shortLabel: 'Address',
        name: 'Address Details',
        req: true,
        icon: MapPin,
        description: 'Provide your valid delivery and billing address details.',
      },
      {
        id: 4,
        key: 'summary',
        shortLabel: 'Summary',
        name: 'Verification Summary',
        req: true,
        icon: CheckCircle,
        description: 'Review your verified details and complete buyer verification.',
      },
    ],
  },
  BUSINESS: {
    buyerType: 'BUSINESS',
    portalTitle: 'Business / Retailer Verification Portal',
    pageTitle: 'Business Identity & Regulatory Compliance',
    badgeText: '✓ VERIFIED BUSINESS BUYER',
    incompleteBadgeText: 'Verification Pending',
    totalRequired: 5,
    steps: [
      {
        id: 1,
        key: 'business',
        shortLabel: 'Business',
        name: 'Business Identity',
        req: true,
        icon: Building2,
        description: 'Verify legal business name, trade name, business type, and registered address.',
      },
      {
        id: 2,
        key: 'pan',
        shortLabel: 'PAN',
        name: 'Business PAN Verification',
        req: true,
        icon: FileCheck2,
        description: 'Verify Permanent Account Number issued in the legal name of the business.',
      },
      {
        id: 3,
        key: 'gstin',
        shortLabel: 'GSTIN',
        name: 'GSTIN Verification (Conditional)',
        req: false,
        icon: FileText,
        description: 'Verify 15-digit GSTIN or select GSTIN Not Applicable if exempt.',
      },
      {
        id: 4,
        key: 'representative',
        shortLabel: 'Representative',
        name: 'Authorized Representative',
        req: true,
        icon: UserCheck,
        description: 'Verify identity, designation, and authorization of official representative.',
      },
      {
        id: 5,
        key: 'bank',
        shortLabel: 'Bank',
        name: 'Bank Account Verification',
        req: true,
        icon: CreditCard,
        description: 'Link active business settlement bank account for commerce transactions.',
      },
      {
        id: 6,
        key: 'udyam',
        shortLabel: 'Udyam',
        name: 'Udyam / MSME Registration (Optional)',
        req: false,
        icon: Award,
        description: 'Verify Udyam Registration Number if registered as MSME / Micro enterprise.',
      },
      {
        id: 7,
        key: 'fssai',
        shortLabel: 'FSSAI / License',
        name: 'FSSAI / Trade License (Conditional)',
        req: false,
        icon: FileBadge,
        description: 'Verify FSSAI license or trade license if required for food/agri operations.',
      },
      {
        id: 8,
        key: 'documents',
        shortLabel: 'Documents',
        name: 'Document Uploads',
        req: true,
        icon: FolderCheck,
        description: 'Upload required business registration certificate, PAN document, bank proof, and authorization letter.',
      },
      {
        id: 9,
        key: 'summary',
        shortLabel: 'Summary',
        name: 'Verification Summary',
        req: true,
        icon: CheckCircle,
        description: 'Review overall compliance checks and obtain verified business buyer status.',
      },
    ],
  },
  BULK_BUYER: {
    buyerType: 'BULK_BUYER',
    portalTitle: 'Wholesale Bulk Buyer Verification Portal',
    pageTitle: 'Enterprise Identity & Comprehensive Verification',
    badgeText: '✓ VERIFIED WHOLESALE BUYER',
    incompleteBadgeText: 'Verification Pending',
    totalRequired: 6,
    steps: [
      {
        id: 1,
        key: 'business',
        shortLabel: 'Org Identity',
        name: 'Business / Organization Identity',
        req: true,
        icon: Building,
        description: 'Verify legal enterprise entity, trade name, and registered corporate office details.',
      },
      {
        id: 2,
        key: 'pan',
        shortLabel: 'Org PAN',
        name: 'Enterprise PAN Verification',
        req: true,
        icon: FileCheck2,
        description: 'Verify 10-character Permanent Account Number of the wholesale enterprise.',
      },
      {
        id: 3,
        key: 'gstin',
        shortLabel: 'GSTIN',
        name: 'GSTIN Verification (Conditional)',
        req: false,
        icon: FileText,
        description: 'Verify GSTIN for tax invoice eligibility or mark GSTIN Not Applicable.',
      },
      {
        id: 4,
        key: 'businessRegistration',
        shortLabel: 'Registration',
        name: 'Business Registration / CIN',
        req: true,
        icon: Building2,
        description: 'Verify company CIN/LLPIN/Registration number based on organization type.',
      },
      {
        id: 5,
        key: 'udyam',
        shortLabel: 'Udyam',
        name: 'Udyam MSME Registration (Optional)',
        req: false,
        icon: Award,
        description: 'Verify optional Udyam MSME registration for priority bulk trading.',
      },
      {
        id: 6,
        key: 'representative',
        shortLabel: 'Authorized Rep',
        name: 'Authorized Signatory / Representative',
        req: true,
        icon: UserCheck,
        description: 'Verify mobile OTP and board authorization of Director/CEO/Authorized Signatory.',
      },
      {
        id: 7,
        key: 'bank',
        shortLabel: 'Bank Account',
        name: 'Corporate Bank Account',
        req: true,
        icon: CreditCard,
        description: 'Link active corporate bank account for high-volume bulk transactions.',
      },
      {
        id: 8,
        key: 'fssai',
        shortLabel: 'Agri License',
        name: 'FSSAI / Commodity Trading License',
        req: false,
        icon: FileBadge,
        description: 'Verify FSSAI, APMC Mandi License, or Agricultural Commodity Trading permit.',
      },
      {
        id: 9,
        key: 'documents',
        shortLabel: 'Doc Review',
        name: 'Document Verification',
        req: true,
        icon: FolderCheck,
        description: 'Upload Certificate of Incorporation/Registration, PAN, Bank proof, and Signatory authorization.',
      },
      {
        id: 10,
        key: 'summary',
        shortLabel: 'Summary',
        name: 'Verification Summary',
        req: true,
        icon: CheckCircle,
        description: 'Finalize enterprise compliance and unlock verified wholesale buyer privileges.',
      },
    ],
  },
};
