import {
  Lock,
  Building2,
  Landmark,
  CreditCard,
  FileCheck2,
  Award,
  Building,
  FileText,
  UserCheck,
  FolderCheck,
} from 'lucide-react';

export const verificationConfigs = {
  farmer: {
    accountType: 'farmer',
    portalTitle: 'Farmer Verification Wizard',
    pageTitle: 'Farmer Identity & Credential Verification',
    badgeText: '✓ VERIFIED FARMER',
    incompleteBadgeText: 'Verification Incomplete',
    totalRequired: 5,
    steps: [
      {
        id: 1,
        key: 'aadhaar',
        shortLabel: 'Identity',
        name: 'Identity Verification',
        req: true,
        icon: Lock,
        description: 'Verify your identity securely using your 12-digit Aadhaar number.',
      },
      {
        id: 2,
        key: 'farmerRegistry',
        shortLabel: 'Farmer ID',
        name: 'Farmer ID / Registry',
        req: true,
        icon: Building2,
        description: 'Confirm your registration status in the state/national farmer database.',
      },
      {
        id: 3,
        key: 'landRecord',
        shortLabel: 'Farm',
        name: 'Land Record / Patta Details',
        req: true,
        icon: Landmark,
        description: 'Verify ownership or cultivation details of your agricultural land.',
      },
      {
        id: 4,
        key: 'bankAccount',
        shortLabel: 'Bank',
        name: 'Bank Account Verification',
        req: true,
        icon: CreditCard,
        description: 'Link your active bank account for direct payments and sales settlements.',
      },
      {
        id: 5,
        key: 'pan',
        shortLabel: 'PAN',
        name: 'PAN Verification',
        req: true,
        icon: FileCheck2,
        description: 'Verify your Permanent Account Number for compliance and payouts.',
      },
      {
        id: 6,
        key: 'pmKisan',
        shortLabel: 'PM-KISAN',
        name: 'PM-KISAN Verification (Optional)',
        req: false,
        icon: Award,
        description: 'Optionally link your PM-KISAN Beneficiary Reference for added credibility.',
      },
    ],
  },
  fpo: {
    accountType: 'fpo',
    portalTitle: 'FPO / FPC Verification Wizard',
    pageTitle: 'Organization Identity & Credential Verification',
    badgeText: '✓ VERIFIED FPO',
    incompleteBadgeText: 'Verification Incomplete',
    totalRequired: 5,
    steps: [
      {
        id: 1,
        key: 'orgIdentity',
        shortLabel: 'Organization',
        name: 'Verify Your Organization',
        req: true,
        icon: Building,
        description: 'Verify legal organization registration, CIN / registration identifier, and state office address.',
      },
      {
        id: 2,
        key: 'orgPan',
        shortLabel: 'Org PAN',
        name: 'Verify Organization PAN',
        req: true,
        icon: FileCheck2,
        description: 'Verify Permanent Account Number issued in the legal name of the organization.',
      },
      {
        id: 3,
        key: 'gstin',
        shortLabel: 'Business',
        name: 'Verify Business Details (GSTIN)',
        req: false,
        icon: FileText,
        description: 'Provide GSTIN registration if applicable, or select GSTIN Not Applicable.',
      },
      {
        id: 4,
        key: 'representative',
        shortLabel: 'Representative',
        name: 'Verify Authorized Representative',
        req: true,
        icon: UserCheck,
        description: 'Verify the identity and authorization of the official representing the organization.',
      },
      {
        id: 5,
        key: 'orgBank',
        shortLabel: 'Org Bank',
        name: 'Verify Organization Bank Account',
        req: true,
        icon: CreditCard,
        description: 'Link organization settlement bank account for direct marketplace transactions.',
      },
      {
        id: 6,
        key: 'orgDocuments',
        shortLabel: 'Documents',
        name: 'Organization Documents',
        req: true,
        icon: FolderCheck,
        description: 'Upload required organization registration certificate, PAN document, bank proof, and authorization letter.',
      },
    ],
  },
};
