import fs from 'fs';

const code = `import i18n from '../i18n';
import {
  Smartphone,
  ShieldCheck,
  MapPin,
  Building2,
  FileCheck2,
  FileText,
  UserCheck,
  CreditCard,
  Award,
  FolderCheck,
  CheckCircle,
  FileBadge,
  Building,
} from 'lucide-react';

export const getBuyerVerificationConfig = (t = (k) => i18n.t(k)) => {
  return {
    INDIVIDUAL: {
      buyerType: 'INDIVIDUAL',
      portalTitle: t('buyerVerificationConfig.INDIVIDUAL.portalTitle'),
      pageTitle: t('buyerVerificationConfig.INDIVIDUAL.pageTitle'),
      badgeText: t('buyerVerificationConfig.INDIVIDUAL.badgeText'),
      incompleteBadgeText: t('buyerVerificationConfig.INDIVIDUAL.incompleteBadgeText'),
      totalRequired: 3,
      steps: [
        {
          id: 1,
          key: 'mobile',
          shortLabel: t('buyerVerificationConfig.INDIVIDUAL.steps.mobile.shortLabel'),
          name: t('buyerVerificationConfig.INDIVIDUAL.steps.mobile.name'),
          req: true,
          icon: Smartphone,
          description: t('buyerVerificationConfig.INDIVIDUAL.steps.mobile.description'),
        },
        {
          id: 2,
          key: 'identity',
          shortLabel: t('buyerVerificationConfig.INDIVIDUAL.steps.identity.shortLabel'),
          name: t('buyerVerificationConfig.INDIVIDUAL.steps.identity.name'),
          req: true,
          icon: ShieldCheck,
          description: t('buyerVerificationConfig.INDIVIDUAL.steps.identity.description'),
        },
        {
          id: 3,
          key: 'address',
          shortLabel: t('buyerVerificationConfig.INDIVIDUAL.steps.address.shortLabel'),
          name: t('buyerVerificationConfig.INDIVIDUAL.steps.address.name'),
          req: true,
          icon: MapPin,
          description: t('buyerVerificationConfig.INDIVIDUAL.steps.address.description'),
        },
        {
          id: 4,
          key: 'summary',
          shortLabel: t('buyerVerificationConfig.INDIVIDUAL.steps.summary.shortLabel'),
          name: t('buyerVerificationConfig.INDIVIDUAL.steps.summary.name'),
          req: true,
          icon: CheckCircle,
          description: t('buyerVerificationConfig.INDIVIDUAL.steps.summary.description'),
        },
      ],
    },
    BUSINESS: {
      buyerType: 'BUSINESS',
      portalTitle: t('buyerVerificationConfig.BUSINESS.portalTitle'),
      pageTitle: t('buyerVerificationConfig.BUSINESS.pageTitle'),
      badgeText: t('buyerVerificationConfig.BUSINESS.badgeText'),
      incompleteBadgeText: t('buyerVerificationConfig.BUSINESS.incompleteBadgeText'),
      totalRequired: 6,
      steps: [
        {
          id: 1,
          key: 'business',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.business.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.business.name'),
          req: true,
          icon: Building,
          description: t('buyerVerificationConfig.BUSINESS.steps.business.description'),
        },
        {
          id: 2,
          key: 'pan',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.pan.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.pan.name'),
          req: true,
          icon: FileCheck2,
          description: t('buyerVerificationConfig.BUSINESS.steps.pan.description'),
        },
        {
          id: 3,
          key: 'gstin',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.gstin.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.gstin.name'),
          req: false,
          icon: FileText,
          description: t('buyerVerificationConfig.BUSINESS.steps.gstin.description'),
        },
        {
          id: 4,
          key: 'businessRegistration',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.businessRegistration.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.businessRegistration.name'),
          req: true,
          icon: Building2,
          description: t('buyerVerificationConfig.BUSINESS.steps.businessRegistration.description'),
        },
        {
          id: 5,
          key: 'representative',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.representative.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.representative.name'),
          req: true,
          icon: UserCheck,
          description: t('buyerVerificationConfig.BUSINESS.steps.representative.description'),
        },
        {
          id: 6,
          key: 'bank',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.bank.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.bank.name'),
          req: true,
          icon: CreditCard,
          description: t('buyerVerificationConfig.BUSINESS.steps.bank.description'),
        },
        {
          id: 7,
          key: 'documents',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.documents.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.documents.name'),
          req: true,
          icon: FolderCheck,
          description: t('buyerVerificationConfig.BUSINESS.steps.documents.description'),
        },
        {
          id: 8,
          key: 'summary',
          shortLabel: t('buyerVerificationConfig.BUSINESS.steps.summary.shortLabel'),
          name: t('buyerVerificationConfig.BUSINESS.steps.summary.name'),
          req: true,
          icon: CheckCircle,
          description: t('buyerVerificationConfig.BUSINESS.steps.summary.description'),
        },
      ],
    },
    BULK_BUYER: {
      buyerType: 'BULK_BUYER',
      portalTitle: t('buyerVerificationConfig.BULK_BUYER.portalTitle'),
      pageTitle: t('buyerVerificationConfig.BULK_BUYER.pageTitle'),
      badgeText: t('buyerVerificationConfig.BULK_BUYER.badgeText'),
      incompleteBadgeText: t('buyerVerificationConfig.BULK_BUYER.incompleteBadgeText'),
      totalRequired: 6,
      steps: [
        {
          id: 1,
          key: 'business',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.business.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.business.name'),
          req: true,
          icon: Building,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.business.description'),
        },
        {
          id: 2,
          key: 'pan',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.pan.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.pan.name'),
          req: true,
          icon: FileCheck2,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.pan.description'),
        },
        {
          id: 3,
          key: 'gstin',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.gstin.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.gstin.name'),
          req: false,
          icon: FileText,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.gstin.description'),
        },
        {
          id: 4,
          key: 'businessRegistration',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.businessRegistration.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.businessRegistration.name'),
          req: true,
          icon: Building2,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.businessRegistration.description'),
        },
        {
          id: 5,
          key: 'udyam',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.udyam.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.udyam.name'),
          req: false,
          icon: Award,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.udyam.description'),
        },
        {
          id: 6,
          key: 'representative',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.representative.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.representative.name'),
          req: true,
          icon: UserCheck,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.representative.description'),
        },
        {
          id: 7,
          key: 'bank',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.bank.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.bank.name'),
          req: true,
          icon: CreditCard,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.bank.description'),
        },
        {
          id: 8,
          key: 'fssai',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.fssai.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.fssai.name'),
          req: false,
          icon: FileBadge,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.fssai.description'),
        },
        {
          id: 9,
          key: 'documents',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.documents.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.documents.name'),
          req: true,
          icon: FolderCheck,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.documents.description'),
        },
        {
          id: 10,
          key: 'summary',
          shortLabel: t('buyerVerificationConfig.BULK_BUYER.steps.summary.shortLabel'),
          name: t('buyerVerificationConfig.BULK_BUYER.steps.summary.name'),
          req: true,
          icon: CheckCircle,
          description: t('buyerVerificationConfig.BULK_BUYER.steps.summary.description'),
        },
      ],
    },
  };
};

export const buyerVerificationConfig = getBuyerVerificationConfig();
`;

fs.writeFileSync('frontend/src/config/buyerVerificationConfig.js', code, 'utf8');
console.log('Successfully generated buyerVerificationConfig.js');
