import fs from 'fs';
import path from 'path';

const basePath = 'c:/Volume D/projects/temp/agri/frontend/src/i18n/locales';
const en = JSON.parse(fs.readFileSync(path.join(basePath, 'en', 'translation.json'), 'utf8'));

const localeOverrides = {
  en: {
    transport: {
      quotations: "Quotations",
      quotationsAvailableSelectionRequired: "{{count}} Quotations Available - Selection Required",
      awaitingTransporterQuotations: "Awaiting Transporter Quotations"
    },
    buyerOrders: {
      produceLabel: "Produce",
      transportLabel: "Transport"
    }
  },
  ta: {
    navigation: {
      home: "முகப்பு",
      marketplace: "சந்தை",
      about: "பற்றி",
      support: "ஆதரவு",
      helpCenter: "உதவி மையம்",
      signIn: "உள்நுழை",
      getStarted: "தொடங்குங்கள்",
      dashboard: "டாஷ்போர்டு",
      logout: "வெளியேறு",
      notifications: "அறிவிப்புகள்",
      cart: "கூடை",
      profile: "சுயவிவரம்",
      settings: "அமைப்புகள்",
      products: "பொருட்கள்",
      orders: "ஆர்டர்கள்",
      sales: "விற்பனை",
      verification: "சரிபார்ப்பு",
      language: "மொழி",
      searchMarketplace: "சந்தையில் தேடுங்கள்",
      account: "கணக்கு",
      wishlist: "விருப்பப்பட்டியல்"
    },
    status: {
      active: "செயலில் உள்ளது",
      verified: "சரிபார்க்கப்பட்டது",
      delivered: "விநியோகிக்கப்பட்டது",
      successful: "வெற்றிகரமானது",
      resolved: "தீர்க்கப்பட்டது",
      pending: "நிலுவையில் உள்ளது",
      pendingVerification: "சரிபார்ப்பு நிலுவையில் உள்ளது",
      created: "உருவாக்கப்பட்டது",
      open: "திறந்துள்ளது",
      confirmed: "உறுதிப்படுத்தப்பட்டது",
      underReview: "பரிசீலனையில் உள்ளது",
      dispatched: "அனுப்பப்பட்டது",
      cancelled: "ரத்து செய்யப்பட்டது",
      rejected: "நிராகரிக்கப்பட்டது",
      failed: "தோல்வியடைந்தது",
      inactive: "செயலற்றது",
      draft: "வரைவு",
      outOfStock: "இருப்பு இல்லை",
      refunded: "பணம் திருப்பித் தரப்பட்டது",
      pendingPayment: "பணம் செலுத்த நிலுவையில் உள்ளது",
      paid: "பணம் செலுத்தப்பட்டது",
      processing: "செயலாக்கத்தில் உள்ளது",
      shipped: "அனுப்பப்பட்டது",
      completed: "நிறைவடைந்தது",
      onboarding: "இணைவு செயல்பாட்டில்",
      suspended: "இடைநீக்கம் செய்யப்பட்டது",
      notStarted: "தொடங்கப்படவில்லை",
      inProgress: "செயல்பாட்டில் உள்ளது",
      approved: "ஒப்புதல் அளிக்கப்பட்டது",
      enabled: "செயல்படுத்தப்பட்டது",
      all: "அனைத்தும்",
      captured: "கைப்பற்றப்பட்டது",
      authorized: "அங்கீகரிக்கப்பட்டது"
    },
    settings: {
      preferences: "விருப்பத்தேர்வுகள்",
      title: "கணக்கு அமைப்புகள்",
      description: "உங்கள் கணினி விருப்பத்தேர்வுகள், பாதுகாப்பு மற்றும் அறிவிப்பு சேனல்களை நிர்வகிக்கவும்.",
      notificationPreferences: "அறிவிப்பு விருப்பத்தேர்வுகள்",
      notificationDescription: "ஆர்டர்கள் மற்றும் இருப்பு மாற்றங்களை AgriBazaar எவ்வாறு அறிவிக்க வேண்டும் என்பதை அமைக்கவும்.",
      emailOrders: "மின்னஞ்சல் ஆர்டர் அறிவிப்புகள்",
      emailOrdersDescription: "புதிய ஆர்டர்கள் மற்றும் நிலை மாற்றங்களுக்கு மின்னஞ்சல் பெறவும்.",
      sms: "SMS அறிவிப்புகள்",
      smsDescription: "அனுப்பல் மற்றும் விநியோகத்தில் உடனடி SMS விழிப்பூட்டல்களைப் பெறவும்.",
      priceAlerts: "சந்தை விலை போக்கு எச்சரிக்கைகள்",
      priceAlertsDescription: "முக்கிய வேளாண் சந்தை விலை மாற்றங்களின் தினசரி சுருக்கம்.",
      security: "பாதுகாப்பு & அணுகல்",
      securityDescription: "கூடுதல் பாதுகாப்பு அடுக்குகளுடன் உங்கள் கணக்கைப் பாதுகாக்கவும்.",
      twoFactor: "இரு காரணி அங்கீகாரம் (2FA)",
      twoFactorDescription: "உள்நுழைவில் OTP சரிபார்ப்பு தேவையாக்கவும்.",
      save: "விருப்பங்களை சேமிக்கவும்",
      saved: "கணக்கு விருப்பத்தேர்வுகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன!",
      help: "உதவி தேவையா?",
      helpDescription: "உங்கள் KYC விவரங்கள் அல்லது விவசாயி சரிபார்ப்பைப் புதுப்பிக்க உதவி தேவைப்பட்டால், தள நிர்வாகியைத் தொடர்பு கொள்ளவும்.",
      platform: "AgriBazaar தளம்",
      architecture: "நேரடி விவசாய வணிக கட்டமைப்பு",
      systemVersionV104production: "அமைப்பின் பதிப்பு: v1.0.4-production"
    },
    transport: {
      quotationsAvailable: "மேற்கோள்கள் கிடைக்கின்றன",
      transporterSelected: "போக்குவரத்து நபர் தேர்ந்தெடுக்கப்பட்டார்",
      awaitingQuotations: "மேற்கோள்களுக்காக காத்திருக்கிறது",
      selectToFinalize: "இறுதி செய்ய மேற்கோளைத் தேர்ந்தெடுக்கவும்.",
      transportersNotified: "போக்குவரத்து நபர்களுக்கு அறிவிக்கப்பட்டது.",
      notRequested: "போக்குவரத்து கோரப்படவில்லை",
      requestTransport: "போக்குவரத்து கோரவும்",
      viewSelectQuotes: "போக்குவரத்து மேற்கோள்களைப் பார்க்கவும்",
      transportFreightStatus: "போக்குவரத்து நிலை",
      pickupLocations: "சேகரிக்கும் இடங்கள் (பல விவசாயிகள்)",
      farmGatePickupLocations: "பண்ணை வாயில் சேகரிக்கும் இடங்கள்",
      deliveryAddress: "விநியோக முகவரி",
      transportDetails: "போக்குவரத்து & சரக்கு விவரங்கள்",
      transportChargeLabel: "போக்குவரத்து & சரக்குக் கட்டணம்",
      requestCreated: "போக்குவரத்துக் கோரிக்கை அனுப்பப்பட்டது! போக்குவரத்து நபர்கள் மேற்கோள்களைச் சமர்ப்பிப்பார்கள்.",
      quotations: "மேற்கோள்கள்",
      quotationsAvailableSelectionRequired: "{{count}} மேற்கோள்கள் உள்ளன - தேர்வு தேவை",
      awaitingTransporterQuotations: "போக்குவரத்து நபர் மேற்கோள்களுக்காக காத்திருக்கிறது"
    },
    buyerOrders: {
      produceLabel: "விளைபொருள்",
      transportLabel: "போக்குவரத்து"
    },
    checkout: {
      orderSummary: "ஆர்டர் கட்டணச் சுருக்கம்",
      productSubtotal: "பொருளின் கூட்டுத்தொகை",
      finalPayableAmount: "இறுதி செலுத்த வேண்டிய தொகை",
      continueCheckout: "செக்அவுட்டைத் தொடரவும்",
      paymentVerified: "பணம் செலுத்துதல் வெற்றிகரமாகச் சரிபார்க்கப்பட்டது!"
    }
  },
  hi: {
    navigation: {
      home: "होम",
      marketplace: "मार्केटप्लेस",
      about: "हमारे बारे में",
      support: "सहायता",
      helpCenter: "सहायता केंद्र",
      signIn: "साइन इन करें",
      getStarted: "शुरू करें",
      dashboard: "डैशबोर्ड",
      logout: "लॉगआउट",
      notifications: "सूचनाएं",
      cart: "कार्ट",
      profile: "प्रोफ़ाइल",
      settings: "सेटिंग्स",
      products: "उत्पाद",
      orders: "ऑर्डर",
      sales: "बिक्री",
      verification: "सत्यापन",
      language: "भाषा",
      searchMarketplace: "मार्केटप्लेस खोजें",
      account: "खाता",
      wishlist: "विशलिस्ट"
    },
    status: {
      active: "सक्रिय",
      verified: "सत्यापित",
      delivered: "डिलीवर किया गया",
      successful: "सफल",
      resolved: "हल किया गया",
      pending: "लंबित",
      pendingVerification: "सत्यापन लंबित",
      created: "निर्मित",
      open: "खुला",
      confirmed: "पुष्टि की गई",
      underReview: "समीक्षाधीन",
      dispatched: "भेज दिया गया",
      cancelled: "रद्द किया गया",
      rejected: "अस्वीकृत",
      failed: "विफल",
      inactive: "निष्क्रिय",
      draft: "ड्राफ्ट",
      outOfStock: "स्टॉक में नहीं",
      refunded: "रिफंड किया गया",
      pendingPayment: "भुगतान लंबित",
      paid: "भुगतान किया गया",
      processing: "प्रसंस्करण जारी",
      shipped: "भेज दिया गया",
      completed: "पूरा हुआ",
      onboarding: "ऑनबोर्डिंग",
      suspended: "निलंबित",
      notStarted: "शुरू नहीं हुआ",
      inProgress: "प्रगति में",
      approved: "स्वीकृत",
      enabled: "सक्षम",
      all: "सभी",
      captured: "कैप्चर किया गया",
      authorized: "अधिकृत"
    },
    settings: {
      preferences: "प्राथमिकताएं",
      title: "खाता सेटिंग्स",
      description: "अपनी सिस्टम प्राथमिकताओं, सुरक्षा और अधिसूचना चैनलों को प्रबंधित करें।",
      notificationPreferences: "अधिसूचना प्राथमिकताएं",
      notificationDescription: "कॉन्फ़िगर करें कि एग्रीबाज़ार आपको ऑर्डर और स्टॉक अपडेट के बारे में कैसे सचेत करता है।",
      emailOrders: "ईमेल ऑर्डर सूचनाएं",
      emailOrdersDescription: "नए ऑर्डर और स्थिति अपडेट के लिए ईमेल प्राप्त करें।",
      sms: "एसएमएस सूचनाएं",
      smsDescription: "डिस्पैच और डिलीवरी पर त्वरित एसएमएस अलर्ट प्राप्त करें।",
      priceAlerts: "बाजार मूल्य रुझान अलर्ट",
      priceAlertsDescription: "शीर्ष कृषि बाजार मूल्य में बदलाव का दैनिक सारांश।",
      security: "सुरक्षा और पहुंच",
      securityDescription: "अतिरिक्त सुरक्षा परतों के साथ अपने खाते की रक्षा करें।",
      twoFactor: "दो-कारक प्रमाणीकरण (2FA)",
      twoFactorDescription: "लॉगिन पर ओटीपी सत्यापन अनिवार्य करें।",
      save: "प्राथमिकताएं सहेजें",
      saved: "खाता प्राथमिकतियां सफलतापूर्वक अपडेट की गईं!",
      help: "क्या मदद चाहिए?",
      helpDescription: "यदि आपको अपने केवाईसी विवरण या किसान सत्यापन को अपडेट करने में सहायता की आवश्यकता है, तो प्लेटफॉर्म प्रशासन से संपर्क करें।",
      platform: "एग्रीबाज़ार प्लेटफॉर्म",
      architecture: "प्रत्यक्ष कृषि वाणिज्य वास्तुकला",
      systemVersionV104production: "सिस्टम संस्करण: v1.0.4-production"
    },
    transport: {
      quotationsAvailable: "कोटेशन उपलब्ध हैं",
      transporterSelected: "ट्रांसपोर्टर का चयन किया गया",
      awaitingQuotations: "कोटेशन की प्रतीक्षा है",
      selectToFinalize: "अंतिम रूप देने के लिए कोटेशन चुनें।",
      transportersNotified: "ट्रांसपोर्टरों को सूचित कर दिया गया है।",
      notRequested: "परिवहन का अनुरोध नहीं किया गया",
      requestTransport: "परिवहन का अनुरोध करें",
      viewSelectQuotes: "परिवहन कोटेशन देखें",
      transportFreightStatus: "परिवहन स्थिति",
      pickupLocations: "पिकअप स्थान (एकाधिक किसान)",
      farmGatePickupLocations: "फार्म गेट पिकअप स्थान",
      deliveryAddress: "डिलीवरी का पता",
      transportDetails: "परिवहन और भाड़ा विवरण",
      transportChargeLabel: "परिवहन और भाड़ा शुल्क",
      requestCreated: "परिवहन अनुरोध भेजा गया! ट्रांसपोर्टर कोटेशन जमा करेंगे।",
      quotations: "कोटेशन",
      quotationsAvailableSelectionRequired: "{{count}} कोटेशन उपलब्ध हैं - चयन आवश्यक है",
      awaitingTransporterQuotations: "ट्रांसपोर्टर कोटेशन की प्रतीक्षा है"
    },
    buyerOrders: {
      produceLabel: "उपज",
      transportLabel: "परिवहन"
    },
    checkout: {
      orderSummary: "ऑर्डर भुगतान सारांश",
      productSubtotal: "उत्पाद उपयोग",
      finalPayableAmount: "अंतिम देय राशि",
      continueCheckout: "चेकआउट जारी रखें",
      paymentVerified: "भुगतान सफलतापूर्वक सत्यापित हो गया!"
    }
  },
  te: {
    navigation: {
      home: "హోమ్",
      marketplace: "మార్కెట్‌ప్లేస్",
      about: "గురించి",
      support: "సపోర్ట్",
      helpCenter: "సహాయ కేంద్రం",
      signIn: "సైన్ ఇన్",
      getStarted: "ప్రారంభించండి",
      dashboard: "డాష్‌బోర్డ్",
      logout: "లాగ్‌అవుట్",
      notifications: "నోటిఫికేషన్లు",
      cart: "కార్ట్",
      profile: "ప్రొఫైల్",
      settings: "సెట్టింగ్‌లు",
      products: "ఉత్పత్తులు",
      orders: "ఆర్డర్‌లు",
      sales: "అమ్మకాలు",
      verification: "పరిశీలన",
      language: "భాష",
      searchMarketplace: "మార్కెట్‌ప్లేస్ శోధించండి",
      account: "ఖాతా",
      wishlist: "విష్‌లిస్ట్"
    },
    status: {
      active: "యాక్టివ్",
      verified: "సరిచూడబడింది",
      delivered: "డెలివరీ చేయబడింది",
      successful: "విజయవంతమైంది",
      resolved: "పరిష్కరించబడింది",
      pending: "పెండింగ్‌లో ఉంది",
      pendingVerification: "పరిశీలన పెండింగ్‌లో ఉంది",
      created: "సృష్టించబడింది",
      open: "ఓపెన్",
      confirmed: "స్థిరీకరించబడింది",
      underReview: "పరిశీలనలో ఉంది",
      dispatched: "రవాణా చేయబడింది",
      cancelled: "రద్దు చేయబడింది",
      rejected: "తిరస్కరించబడింది",
      failed: "విఫలమైంది",
      inactive: "నిష్క్రియం",
      draft: "డ్రాఫ్ట్",
      outOfStock: "స్టాక్ లేదు",
      refunded: "రీఫండ్ చేయబడింది",
      pendingPayment: "చెల్లింపు పెండింగ్‌లో ఉంది",
      paid: "చెల్లించబడింది",
      processing: "ప్రాసెసింగ్ జరుగుతోంది",
      shipped: "షిప్ చేయబడింది",
      completed: "పూర్తయింది",
      onboarding: "ఆన్‌బోర్డింగ్",
      suspended: "సస్పెండ్ చేయబడింది",
      notStarted: "ప్రారంభం కాలేదు",
      inProgress: "పురోగతిలో ఉంది",
      approved: "ఆమోదించబడింది",
      enabled: "సక్షమం చేయబడింది",
      all: "అన్నీ",
      captured: "క్యాప్చర్ చేయబడింది",
      authorized: "అధికారికం"
    },
    settings: {
      preferences: "ప్రాధాన్యతలు",
      title: "ఖాతా సెట్టింగ్‌లు",
      description: "మీ సిస్టమ్ ప్రాధాన్యతలు, భద్రత మరియు నోటిఫికేషన్ ఛానెల్‌లను నిర్వహించండి.",
      notificationPreferences: "నోటిఫికేషన్ ప్రాధాన్యతలు",
      notificationDescription: "ఆర్డర్‌లు మరియు స్టాక్ అప్‌డేట్‌లను అగ్రిబజార్ మీకు ఎలా హెచ్చరించాలో కాన్ఫిగర్ చేయండి.",
      emailOrders: "ఈమెయిల్ ఆర్డర్ నోటిఫికేషన్లు",
      emailOrdersDescription: "కొత్త ఆర్డర్‌లు మరియు స్థితి అప్‌డేట్‌ల కోసం ఇమెయిల్‌లను పొందండి.",
      sms: "SMS నోటిఫికేషన్లు",
      smsDescription: "డిస్పాచ్ మరియు డెలివరీలో తక్షణ SMS హెచ్చరికలను పొందండి.",
      priceAlerts: "మార్కెట్ ధరల ధోరణి అలర్ట్‌లు",
      priceAlertsDescription: "ముఖ్యమైన వ్యవసాయ మార్కెట్ ధరల మార్పుల రోజువారీ సారాంశం.",
      security: "భద్రత & ప్రాప్యత",
      securityDescription: "అదనపు భద్రతా పొరలతో మీ ఖాతాను రక్షించుకోండి.",
      twoFactor: "టూ-ఫాక్టర్ అథెంటికేషన్ (2FA)",
      twoFactorDescription: "లాగిన్ చేసేటప్పుడు OTP పరిశీలనను తప్పనిసరి చేయండి.",
      save: "ప్రాధాన్యతలను సేవ్ చేయండి",
      saved: "ఖాతా ప్రాధాన్యతలు విజయవంతంగా అప్‌డేట్ చేయబడ్డాయి!",
      help: "సహాయం కావాలా?",
      helpDescription: "మీ KYC వివరాలు లేదా రైతు పరిశీలనను అప్‌డేట్ చేయడంలో సహాయం కావాలంటే, ప్లాట్‌ఫారమ్ అడ్మినిస్ట్రేషన్‌ను సంప్రదించండి.",
      platform: "అగ్రిబజార్ ప్లాట్‌ఫారమ్",
      architecture: "నేరుగా వ్యవసాయ వాణిజ్య నిర్మాణం",
      systemVersionV104production: "సిస్టమ్ వెర్షన్: v1.0.4-production"
    },
    transport: {
      quotationsAvailable: "కోటేషన్‌లు అందుబాటులో ఉన్నాయి",
      transporterSelected: "ట్రాన్స్‌పోర్టర్ ఎంపిక చేయబడ్డారు",
      awaitingQuotations: "కోటేషన్ల కోసం నిరీక్షణ",
      selectToFinalize: "ముగించడానికి కోటేషన్‌ను ఎంచుకోండి.",
      transportersNotified: "ట్రాన్స్‌పోర్టర్లకు సమాచారం అందించబడింది.",
      notRequested: "రవాణా కోరబడలేదు",
      requestTransport: "రవాణాను అభ్యర్థించండి",
      viewSelectQuotes: "రవాణా కోటేషన్‌లను చూడండి",
      transportFreightStatus: "రవాణా స్థితి",
      pickupLocations: "పికప్ స్థానాలు (బహుళ రైతులు)",
      farmGatePickupLocations: "ఫారమ్ గేట్ పికప్ స్థానాలు",
      deliveryAddress: "డెలివరీ చిరునామా",
      transportDetails: "రవాణా & ఫ్రైట్ వివరాలు",
      transportChargeLabel: "రవాణా & ఫ్రైట్ ఛార్జీలు",
      requestCreated: "రవాణా అభ్యర్థన పంపబడింది! ట్రాన్స్‌పోర్టర్లు కోటేషన్లను సమర్పిస్తారు.",
      quotations: "కోటేషన్‌లు",
      quotationsAvailableSelectionRequired: "{{count}} కోటేషన్‌లు అందుబాటులో ఉన్నాయి - ఎంపిక అవసరం",
      awaitingTransporterQuotations: "ట్రాన్స్‌పోర్టర్ కోటేషన్ల కోసం నిరీక్షణ"
    },
    buyerOrders: {
      produceLabel: "ఉత్పత్తి",
      transportLabel: "రవాణా"
    },
    checkout: {
      orderSummary: "ఆర్డర్ చెల్లింపు సారాంశం",
      productSubtotal: "ఉత్పత్తి సబ్‌టోటల్",
      finalPayableAmount: "చివరి చెల్లించవలసిన మొత్తం",
      continueCheckout: "చెక్‌అవుట్‌ను కొనసాగించండి",
      paymentVerified: "చెల్లింపు విజయవంతంగా ధృవీకరించబడింది!"
    }
  },
  kn: {
    navigation: {
      home: "ಮುಖಪುಟ",
      marketplace: "ಮಾರುಕಟ್ಟೆ",
      about: "ನಮ್ಮ ಬಗ್ಗೆ",
      support: "ಬೆಂಬಲ",
      helpCenter: "ಸಹಾಯ ಕೇಂದ್ರ",
      signIn: "ಸೈನ್ ಇನ್",
      getStarted: "ಪ್ರಾರಂಭಿಸಿ",
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      logout: "ಲಾಗ್ ಔಟ್",
      notifications: "ಸೂಚನೆಗಳು",
      cart: "ಕಾರ್ಟ್",
      profile: "ಪ್ರೊಫೈಲ್",
      settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
      products: "ಉತ್ಪನ್ನಗಳು",
      orders: "ಆದೇಶಗಳು",
      sales: "ಮಾರಾಟ",
      verification: "ಪರಿಶೀಲನೆ",
      language: "ಭಾಷೆ",
      searchMarketplace: "ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ",
      account: "ಖಾತೆ",
      wishlist: "ಆಸೆಪಟ್ಟಿ"
    },
    status: {
      active: "ಸಕ್ರಿಯ",
      verified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
      delivered: "ವಿತರಿಸಲಾಗಿದೆ",
      successful: "ಯಶಸ್ವಿಯಾಗಿದೆ",
      resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
      pending: "ಬಾಕಿ ಇದೆ",
      pendingVerification: "ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ",
      created: "ಸೃಷ್ಟಿಸಲಾಗಿದೆ",
      open: "ತೆರೆದಿದೆ",
      confirmed: "ಖಚಿತಪಡಿಸಲಾಗಿದೆ",
      underReview: "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
      dispatched: "ರವಾನಿಸಲಾಗಿದೆ",
      cancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
      rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
      failed: "ವಿಫಲವಾಗಿದೆ",
      inactive: "ನಿಷ್ಕ್ರಿಯ",
      draft: "ಕರಡು",
      outOfStock: "ಸ್ಟಾಕ್ ಇಲ್ಲ",
      refunded: "ಮರುಪಾವತಿಸಲಾಗಿದೆ",
      pendingPayment: "ಪಾವತಿ ಬಾಕಿ ಇದೆ",
      paid: "ಪಾವತಿಸಲಾಗಿದೆ",
      processing: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ",
      shipped: "ರವಾನಿಸಲಾಗಿದೆ",
      completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
      onboarding: "ಆನ್‌ಬೋರ್ಡಿಂಗ್",
      suspended: "ಅಮಾನತುಗೊಳಿಸಲಾಗಿದೆ",
      notStarted: "ಪ್ರಾರಂಭವಾಗಿಲ್ಲ",
      inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
      approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
      enabled: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
      all: "ಎಲ್ಲವೂ",
      captured: "ಹಿಡಿಯಲಾಗಿದೆ",
      authorized: "ಅಧಿಕೃತಗೊಳಿಸಲಾಗಿದೆ"
    },
    settings: {
      preferences: "ಆದ್ಯತೆಗಳು",
      title: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
      description: "ನಿಮ್ಮ ಸಿಸ್ಟಮ್ ಆದ್ಯತೆಗಳು, ಭದ್ರತೆ ಮತ್ತು ಸೂಚನೆ ಚಾನೆಲ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
      notificationPreferences: "ಸೂಚನೆ ಆದ್ಯತೆಗಳು",
      notificationDescription: "ಆದೇಶಗಳು ಮತ್ತು ಸ್ಟಾಕ್ ನವೀಕರಣಗಳ ಬಗ್ಗೆ ಅಗ್ರಿಬಜಾರ್ ನಿಮಗೆ ಹೇಗೆ ಎಚ್ಚರಿಸಬೇಕೆಂದು ಹೊಂದಿಸಿ.",
      emailOrders: "ಇಮೇಲ್ ಆದೇಶ ಸೂಚನೆಗಳು",
      emailOrdersDescription: "ಹೊಸ ಆದೇಶಗಳು ಮತ್ತು ಸ್ಥಿತಿ ನವೀಕರಣಗಳಿಗಾಗಿ ಇಮೇಲ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.",
      sms: "SMS ಸೂಚನೆಗಳು",
      smsDescription: "ರವಾನೆ ಮತ್ತು ವಿತರಣೆಯಲ್ಲಿ ತ್ವರಿತ SMS ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
      priceAlerts: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಪ್ರವೃತ್ತಿ ಎಚ್ಚರಿಕೆಗಳು",
      priceAlertsDescription: "ಉನ್ನತ ಕೃಷಿ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಬದಲಾವಣೆಗಳ ದೈನಂದಿನ ಸಾರಾಂಶ.",
      security: "ಭದ್ರತೆ ಮತ್ತು ಪ್ರವೇಶ",
      securityDescription: "ಹೆಚ್ಚುವರಿ ಭದ್ರತಾ ಪದರಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಕ್ಷಿಸಿ.",
      twoFactor: "ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ (2FA)",
      twoFactorDescription: "ಲಾಗಿನ್‌ನಲ್ಲಿ OTP ಪರಿಶೀಲನೆ ಅಗತ್ಯಗೊಳಿಸಿ.",
      save: "ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ",
      saved: "ಖಾತೆ ಆದ್ಯತೆಗಳು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲ್ಪಟ್ಟಿವೆ!",
      help: "ಸಹಾಯ ಬೇಕೇ?",
      helpDescription: "ನಿಮ್ಮ KYC ವಿವರಗಳು ಅಥವಾ ರೈತ ಪರಿಶೀಲನೆಯನ್ನು ನವೀಕರಿಸಲು ಸಹಾಯ ಬೇಕಾದರೆ, ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಆಡಳಿತವನ್ನು ಸಂಪರ್ಕಿಸಿ.",
      platform: "ಅಗ್ರಿಬಜಾರ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
      architecture: "ನೇರ ಕೃಷಿ ವಾಣಿಜ್ಯ ರಚನೆ",
      systemVersionV104production: "ಸಿಸ್ಟಮ್ ಆವೃತ್ತಿ: v1.0.4-production"
    },
    transport: {
      quotationsAvailable: "ಉಲ್ಲೇಖಗಳು ಲಭ್ಯವಿವೆ",
      transporterSelected: "ಸಾರಿಗೆದಾರರನ್ನು ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ",
      awaitingQuotations: "ಉಲ್ಲೇಖಗಳಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
      selectToFinalize: "ಅಂತಿಮಗೊಳಿಸಲು ಉಲ್ಲೇಖವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
      transportersNotified: "ಸಾರಿಗೆದಾರರಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.",
      notRequested: "ಸಾರಿಗೆ ವಿನಂತಿಸಲಾಗಿಲ್ಲ",
      requestTransport: "ಸಾರಿಗೆ ವಿನಂತಿಸಿ",
      viewSelectQuotes: "ಸಾರಿಗೆ ಉಲ್ಲೇಖಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
      transportFreightStatus: "ಸಾರಿಗೆ ಸ್ಥಿತಿ",
      pickupLocations: "ಪಿಕಪ್ ಸ್ಥಳಗಳು (ಹಲವು ರೈತರು)",
      farmGatePickupLocations: "ಫಾರ್ಮ್ ಗೇಟ್ ಪಿಕಪ್ ಸ್ಥಳಗಳು",
      deliveryAddress: "ವಿತರಣಾ ವಿಳಾಸ",
      transportDetails: "ಸಾರಿಗೆ ಮತ್ತು ಸರಕು ವಿವರಗಳು",
      transportChargeLabel: "ಸಾರಿಗೆ ಮತ್ತು ಸರಕು ಶುಲ್ಕ",
      requestCreated: "ಸಾರಿಗೆ ವಿನಂತಿಯನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ! ಸಾರಿಗೆದಾರರು ಉಲ್ಲೇಖಗಳನ್ನು ಸಲ್ಲಿಸುತ್ತಾರೆ.",
      quotations: "ಉಲ್ಲೇಖಗಳು",
      quotationsAvailableSelectionRequired: "{{count}} ಉಲ್ಲೇಖಗಳು ಲಭ್ಯವಿವೆ - ಆಯ್ಕೆ ಅಗತ್ಯವಿದೆ",
      awaitingTransporterQuotations: "ಸಾರಿಗೆದಾರರ ಉಲ್ಲೇಖಗಳಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ"
    },
    buyerOrders: {
      produceLabel: "ಉತ್ಪನ್ನ",
      transportLabel: "ಸಾರಿಗೆ"
    },
    checkout: {
      orderSummary: "ಆದೇಶ ಪಾವತಿ ಸಾರಾಂಶ",
      productSubtotal: "ಉತ್ಪನ್ನಗಳ ಒಟ್ಟು",
      finalPayableAmount: "ಅಂತಿಮ ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
      continueCheckout: "ಚೆಕ್‌ಔಟ್ ಮುಂದುವರಿಸಿ",
      paymentVerified: "ಪಾವತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ!"
    }
  },
  ml: {
    navigation: {
      home: "ഹോം",
      marketplace: "മാർക്കറ്റ് പ്ലേസ്",
      about: "ഞങ്ങളെ കുറിച്ച്",
      support: "സപ്പോർട്ട്",
      helpCenter: "ഹെൽപ്പ് സെന്റർ",
      signIn: "സൈൻ ഇൻ",
      getStarted: "ആരംഭിക്കുക",
      dashboard: "ഡാഷ്‌ബോർഡ്",
      logout: "ലോഗ് ഔട്ട്",
      notifications: "അറിയിപ്പുകൾ",
      cart: "കാർട്ട്",
      profile: "പ്രൊഫൈൽ",
      settings: "സെറ്റിംഗ്സ്",
      products: "ഉൽപ്പന്നങ്ങൾ",
      orders: "ഓർഡറുകൾ",
      sales: "വില്പന",
      verification: "വെരിഫിക്കേഷൻ",
      language: "ഭാഷ",
      searchMarketplace: "മാർക്കറ്റ് പ്ലേസ് തിരയുക",
      account: "അക്കൗണ്ട്",
      wishlist: "വിഷ്‌ലിസ്റ്റ്"
    },
    status: {
      active: "സജീവം",
      verified: "വെരിഫൈ ചെയ്തു",
      delivered: "ഡെലിവർ ചെയ്തു",
      successful: "വിജയകരം",
      resolved: "പരിഹരിച്ചു",
      pending: "പെൻഡിംഗ്",
      pendingVerification: "വെരിഫിക്കേഷൻ കാത്തിരിക്കുന്നു",
      created: "സൃഷ്ടിച്ചു",
      open: "ഓപ്പൺ",
      confirmed: "സ്ഥിരീകരിച്ചു",
      underReview: "പരിശോധനയിൽ",
      dispatched: "ഡിസ്പാച്ച് ചെയ്തു",
      cancelled: "റദ്ദാക്കി",
      rejected: "നിരസിച്ചു",
      failed: "പരാജയപ്പെട്ടു",
      inactive: "നിഷ്ക്രിയം",
      draft: "ഡ്രാഫ്റ്റ്",
      outOfStock: "സ്റ്റോക്കില്ല",
      refunded: "റിഫണ്ട് ചെയ്തു",
      pendingPayment: "പേയ്‌മെന്റ് ബാക്കിയുണ്ട്",
      paid: "പണം നൽകി",
      processing: "പ്രോസസ്സ് ചെയ്യുന്നു",
      shipped: "അയച്ചു",
      completed: "പൂർത്തിയായി",
      onboarding: "ഓൺബോർഡിംഗ്",
      suspended: "സസ്‌പെൻഡ് ചെയ്തു",
      notStarted: "ആരംഭിച്ചിട്ടില്ല",
      inProgress: "പുരോഗമിക്കുന്നു",
      approved: "അംഗീകരിച്ചു",
      enabled: "സജ്ജമാക്കി",
      all: "എല്ലാം",
      captured: "സ്വീകരിച്ചു",
      authorized: "അംഗീകരിച്ചു"
    },
    settings: {
      preferences: "മുൻഗണനകൾ",
      title: "അക്കൗണ്ട് സെറ്റിംഗ്സ്",
      description: "നിങ്ങളുടെ സിസ്റ്റം മുൻഗണനകൾ, സുരക്ഷ, നോട്ടിഫിക്കേഷൻ ചാനലുകൾ എന്നിവ കൈകാര്യം ചെയ്യുക.",
      notificationPreferences: "നോട്ടിഫിക്കേഷൻ മുൻഗണനകൾ",
      notificationDescription: "ഓർഡറുകളെക്കുറിച്ചും സ്റ്റോക്ക് അപ്‌ഡേറ്റുകളെക്കുറിച്ചും അഗ്രിബസാർ എങ്ങനെ മുന്നറിയിപ്പ് നൽകണമെന്ന് കോൺഫിഗർ ചെയ്യുക.",
      emailOrders: "ഇമെയിൽ ഓർഡർ അറിയിപ്പുകൾ",
      emailOrdersDescription: "പുതിയ ഓർഡറുകൾക്കും സ്റ്റാറ്റസ് അപ്‌ഡേറ്റുകൾക്കുമായി ഇമെയിലുകൾ സ്വീകരിക്കുക.",
      sms: "SMS അറിയിപ്പുകൾ",
      smsDescription: "ഡിസ്പാച്ചിലും ഡെലിവറിയിലും ഉടനടി SMS മുന്നറിയിപ്പുകൾ നേടുക.",
      priceAlerts: "മാർക്കറ്റ് വില വിവര മുന്നറിയിപ്പുകൾ",
      priceAlertsDescription: "പ്രധാന കാർഷിക വിപണി വില മാറ്റങ്ങളുടെ ദിനചര്യ ചുരുക്കം.",
      security: "സുരക്ഷയും ആക്സസും",
      securityDescription: "കൂടുതൽ സുരക്ഷാ ലെയറുകൾ ഉപയോഗിച്ച് നിങ്ങളുടെ അക്കൗണ്ട് സംരക്ഷിക്കുക.",
      twoFactor: "ടു-ഫാക്ടർ ഓതന്റിക്കേഷൻ (2FA)",
      twoFactorDescription: "ലോഗിൻ ചെയ്യുമ്പോൾ OTP വെരിഫിക്കേഷൻ നിർബന്ധമാക്കുക.",
      save: "മുൻഗണനകൾ സേവ് ചെയ്യുക",
      saved: "അക്കൗണ്ട് മുൻഗണനകൾ വിജയകരമായി പുതുക്കി!",
      help: "സഹായം വേണോ?",
      helpDescription: "നിങ്ങളുടെ KYC വിവരങ്ങളോ കർഷക വെരിഫിക്കേഷനോ അപ്‌ഡേറ്റ് ചെയ്യാൻ സഹായം വേണമെങ്കിൽ, പ്ലാറ്റ്‌ഫോം അഡ്മിനിസ്ട്രേഷനുമായി ബന്ധപ്പെടുക.",
      platform: "അഗ്രിബസാർ പ്ലാറ്റ്‌ഫോം",
      architecture: "ഡയറക്ട് അഗ്രികൾച്ചർ കൊമേഴ്‌സ് ആർക്കിടെക്ചർ",
      systemVersionV104production: "സിസ്റ്റം വേർഷൻ: v1.0.4-production"
    },
    transport: {
      quotationsAvailable: "കൊട്ടേഷനുകൾ ലഭ്യമാണ്",
      transporterSelected: "ട്രാൻസ്പോർട്ടറെ തിരഞ്ഞെടുത്തു",
      awaitingQuotations: "കൊട്ടേഷനുകൾക്കായി കാത്തിരിക്കുന്നു",
      selectToFinalize: "അന്തിമമാക്കാൻ കൊട്ടേഷൻ തിരഞ്ഞെടുക്കുക.",
      transportersNotified: "ട്രാൻസ്പോർട്ടർമാരെ അറിയിച്ചു.",
      notRequested: "ഗതാഗതം ആവശ്യപ്പെട്ടിട്ടില്ല",
      requestTransport: "ഗതാഗതം അഭ്യർത്ഥിക്കുക",
      viewSelectQuotes: "ട്രാൻസ്പോർട്ട് കൊട്ടേഷനുകൾ കാണുക",
      transportFreightStatus: "ഗതാഗത സ്റ്റാറ്റസ്",
      pickupLocations: "പിക്കപ്പ് ലൊക്കേഷനുകൾ (മൾട്ടി-ഫാർമർ)",
      farmGatePickupLocations: "ഫാം ഗേറ്റ് പിക്കപ്പ് ലൊക്കേഷനുകൾ",
      deliveryAddress: "ഡെലിവറി വിലാസം",
      transportDetails: "ഗതാഗത ഫ്രൈറ്റ് വിവരങ്ങൾ",
      transportChargeLabel: "ഗതാഗത ഫ്രൈറ്റ് ചാർജ്",
      requestCreated: "ഗതാഗത അഭ്യർത്ഥന അയച്ചു! ട്രാൻസ്പോർട്ടർമാർ കൊട്ടേഷനുകൾ സമർപ്പിക്കും.",
      quotations: "കൊട്ടേഷനുകൾ",
      quotationsAvailableSelectionRequired: "{{count}} കൊട്ടേഷനുകൾ ലഭ്യമാണ് - തിരഞ്ഞെടുക്കൽ ആവശ്യമാണ്",
      awaitingTransporterQuotations: "ട്രാൻസ്പോർട്ടർ കൊട്ടേഷനുകൾക്കായി കാത്തിരിക്കുന്നു"
    },
    buyerOrders: {
      produceLabel: "ഉൽപ്പന്നം",
      transportLabel: "ഗതാഗതം"
    },
    checkout: {
      orderSummary: "ഓർഡർ പേയ്‌മെന്റ് സംഗ്രഹം",
      productSubtotal: "ഉൽപ്പന്ന തുക",
      finalPayableAmount: "ആകെ നൽകേണ്ട തുക",
      continueCheckout: "ചെക്കൗട്ട് തുടരുക",
      paymentVerified: "പേയ്‌മെന്റ് വിജയകരമായി സ്ഥിരീകരിച്ചു!"
    }
  }
};

const locales = ['en', 'ta', 'hi', 'te', 'kn', 'ml'];

locales.forEach((loc) => {
  const filePath = path.join(basePath, loc, 'translation.json');
  let locData = fs.existsSync(filePath) ? JSON.parse(fs.readFileSync(filePath, 'utf8')) : {};

  // Deep update override keys for specific locale if available
  if (localeOverrides[loc]) {
    const overrides = localeOverrides[loc];
    Object.keys(overrides).forEach((sec) => {
      if (!locData[sec]) locData[sec] = {};
      Object.keys(overrides[sec]).forEach((key) => {
        locData[sec][key] = overrides[sec][key];
      });
    });
  }

  // Ensure all keys from en/translation.json are recursively copied/updated
  function syncKeys(source, target) {
    Object.keys(source).forEach((k) => {
      if (typeof source[k] === 'object' && source[k] !== null && !Array.isArray(source[k])) {
        if (!target[k] || typeof target[k] !== 'object') target[k] = {};
        syncKeys(source[k], target[k]);
      } else {
        if (!target[k]) {
          target[k] = source[k];
        }
      }
    });
  }

  syncKeys(en, locData);

  fs.writeFileSync(filePath, JSON.stringify(locData, null, 2) + '\n', 'utf8');
  console.log(`Updated ${loc}/translation.json successfully.`);
});
