import fs from 'fs';
import path from 'path';

const untranslatedMap = JSON.parse(fs.readFileSync('scripts/untranslatedMap.json', 'utf8'));
const locales = ['ta', 'hi', 'te', 'kn', 'ml'];

// Dedicated dictionary of common terms and patterns across Indian languages
const dictionary = {
  ta: {
    // General terms
    "Verify": "சரிபார்க்கவும்",
    "Verified": "சரிபார்க்கப்பட்டது",
    "Pending": "நிலுவையில் உள்ளது",
    "Required": "கட்டாயமானது",
    "Optional": "விருப்பத்திற்குரியது",
    "Status": "நிலை",
    "Document": "ஆவணம்",
    "Certificate": "சான்றிதழ்",
    "Upload": "பதிவேற்று",
    "Download": "பதிவிறக்கு",
    "Cancel": "ரத்து செய்",
    "Confirm": "உறுதிப்படுத்து",
    "Save": "சேமி",
    "Edit": "திருத்து",
    "Delete": "நீக்கு",
    "Next": "அடுத்து",
    "Back": "பின்னால்",
    "Submit": "சமர்ப்பி",
    "Search": "தேடு",
    "Filter": "வடிகட்டு",
    "Details": "விவரங்கள்",
    "Identity": "அடையாளம்",
    "Organization": "அமைப்பு",
    "Representative": "பிரதிநிதி",
    "Address": "முகவரி",
    "Pincode": "அஞ்சல் குறியீடு",
    "Mobile": "மொபைல் எண்",
    "Email": "மின்னஞ்சல்",
    "District": "மாவட்டம்",
    "State": "மாநிலம்",
    "Village": "கிராமம்",
    "Taluk": "தாலுகா",
    "PATTA": "பட்டா",
    "SURVEY": "சர்வே எண்",
    "BANK": "வங்கி",
    "ACCOUNT": "கணக்கு எண்",
    "IFSC": "IFSC குறியீடு",
    "PAN": "பான் கார்டு",
    "Aadhaar": "ஆதார்",
    "Farmer": "விவசாயி",
    "Buyer": "வாங்குபவர்",
    "Transporter": "போக்குவரத்தாளர்",
    "Admin": "நிர்வாகி",
    "Order": "ஆர்டர்",
    "Product": "தயாரிப்பு",
    "Quantity": "அளவு",
    "Price": "விலை",
    "Total": "மொத்தம்",
    "Revenue": "வருவாய்",
    "Shipment": "சரக்கு விநியோகம்",
    "Quote": "விலைப்புள்ளி",
    "Vehicle": "வாகனம்",
    "Blockchain": "பிளாக்செயின்",
    "Hash": "சங்கேத குறியீடு",
    "Tx": "பரிவர்த்தனை"
  },
  hi: {
    "Verify": "सत्यापित करें",
    "Verified": "सत्यापित",
    "Pending": "लंबित",
    "Required": "आवश्यक",
    "Optional": "वैकल्पिक",
    "Status": "स्थिति",
    "Document": "दस्तावेज़",
    "Certificate": "प्रमाण पत्र",
    "Upload": "अपलोड करें",
    "Download": "डाउनलोड करें",
    "Cancel": "रद्द करें",
    "Confirm": "पुष्टि करें",
    "Save": "सहेजें",
    "Edit": "संपादित करें",
    "Delete": "हटाएं",
    "Next": "आगे",
    "Back": "पीछे",
    "Submit": "सबमिट करें",
    "Search": "खोजें",
    "Filter": "फ़िल्टर",
    "Details": "विवरण",
    "Identity": "पहचान",
    "Organization": "संगठन",
    "Representative": "प्रतिनिधि",
    "Address": "पता",
    "Pincode": "पिनकोड",
    "Mobile": "मोबाइल नंबर",
    "Email": "ईमेल",
    "District": "जिला",
    "State": "राज्य",
    "Village": "गांव",
    "Taluk": "तालुका",
    "PATTA": "पट्टा",
    "SURVEY": "सर्वे संख्या",
    "BANK": "बैंक",
    "ACCOUNT": "खाता",
    "IFSC": "IFSC कोड",
    "PAN": "पैन कार्ड",
    "Aadhaar": "आधार",
    "Farmer": "किसान",
    "Buyer": "खरीदार",
    "Transporter": "परिवहनकर्ता",
    "Admin": "प्रशासक",
    "Order": "ऑर्डर",
    "Product": "उत्पाद",
    "Quantity": "मात्रा",
    "Price": "मूल्य",
    "Total": "कुल",
    "Revenue": "राजस्व",
    "Shipment": "शिपमेंट",
    "Quote": "कोटेशन",
    "Vehicle": "वाहन",
    "Blockchain": "ब्लॉकचेन",
    "Hash": "हैश",
    "Tx": "लेनदेन"
  },
  te: {
    "Verify": "ధృవీకరించు",
    "Verified": "ధృవీకరించబడింది",
    "Pending": "పెండింగ్",
    "Required": "అవసరం",
    "Optional": "ఐచ్ఛికం",
    "Status": "స్థితి",
    "Document": "పత్రం",
    "Certificate": "ధృవీకరణ పత్రం",
    "Upload": "అప్‌లోడ్ చేయి",
    "Download": "డౌన్‌లోడ్ చేయి",
    "Cancel": "రద్దు చేయి",
    "Confirm": "స్థిరీకరించు",
    "Save": "సేవ్ చేయి",
    "Edit": "సవరించు",
    "Delete": "తొలగించు",
    "Next": "తరువాత",
    "Back": "వెనుకకు",
    "Submit": "సమర్పించు",
    "Search": "శోధించు",
    "Filter": "ఫిల్టర్",
    "Details": "వివరాలు",
    "Identity": "గుర్తింపు",
    "Organization": "సంస్థ",
    "Representative": "ప్రతినిధి",
    "Address": "చిరునామా",
    "Pincode": "పిన్‌కోడ్",
    "Mobile": "మొబైల్ సంఖ్య",
    "Email": "ఈమెయిల్",
    "District": "జిల్లా",
    "State": "రాష్ట్రం",
    "Village": "గ్రామం",
    "Taluk": "తాలూకా",
    "PATTA": "పట్టా",
    "SURVEY": "సర్వే సంఖ్య",
    "BANK": "బ్యాంక్",
    "ACCOUNT": "ఖాతా",
    "IFSC": "IFSC కోడ్",
    "PAN": "పాన్ కార్డ్",
    "Aadhaar": "ఆధార్",
    "Farmer": "రైతు",
    "Buyer": "కొనుగోలుదారు",
    "Transporter": "రవాణాదారు",
    "Admin": "అడ్మిన్",
    "Order": "ఆర్డర్",
    "Product": "ఉత్పత్తి",
    "Quantity": "పరిమాణం",
    "Price": "ధర",
    "Total": "మొత్తం",
    "Revenue": "రాబడి",
    "Shipment": "రవాణా విడత",
    "Quote": "కోటేషన్",
    "Vehicle": "వాహనం",
    "Blockchain": "బ్లాక్‌చైన్",
    "Hash": "హాష్",
    "Tx": "లావాదేవీ"
  },
  kn: {
    "Verify": "ದೃಢೀಕರಿಸಿ",
    "Verified": "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    "Pending": "ಬಾಕಿ ಇದೆ",
    "Required": "ಅಗತ್ಯವಿದೆ",
    "Optional": "ಐಚ್ಛಿಕ",
    "Status": "ಸ್ಥಿತಿ",
    "Document": "ದಾಖಲೆ",
    "Certificate": "ಪ್ರಮಾಣಪತ್ರ",
    "Upload": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "Download": "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "Cancel": "ರದ್ದುಗೊಳಿಸಿ",
    "Confirm": "ಖಚಿತಪಡಿಸಿ",
    "Save": "ಉಳಿಸಿ",
    "Edit": "ಸಂಪಾದಿಸಿ",
    "Delete": "ತೆಗೆದುಹಾಕಿ",
    "Next": "ಮುಂದೆ",
    "Back": "ಹಿಂದೆ",
    "Submit": "ಸಲ್ಲಿಸಿ",
    "Search": "ಹುಡುಕಿ",
    "Filter": "ಫಿಲ್ಟರ್",
    "Details": "ವಿವರಗಳು",
    "Identity": "ಗುರುತು",
    "Organization": "ಸಂಸ್ಥೆ",
    "Representative": "ಪ್ರತಿನಿಧಿ",
    "Address": "ವಿಳಾಸ",
    "Pincode": "ಪಿನ್‌ಕೋಡ್",
    "Mobile": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    "Email": "ಇಮೇಲ್",
    "District": "ಜಿಲ್ಲೆ",
    "State": "ರಾಜ್ಯ",
    "Village": "ಗ್ರಾಮ",
    "Taluk": "ತಾಲೂಕು",
    "PATTA": "ಪಟ್ಟಾ",
    "SURVEY": "ಸರ್ವೇ ಸಂಖ್ಯೆ",
    "BANK": "ಬ್ಯಾಂಕ್",
    "ACCOUNT": "ಖಾತೆ",
    "IFSC": "IFSC ಕೋಡ್",
    "PAN": "ಪ್ಯಾನ್ ಕಾರ್ಡ್",
    "Aadhaar": "ಆಧಾರ್",
    "Farmer": "ರೈತ",
    "Buyer": "ಖರೀದಿದಾರ",
    "Transporter": "ಸಾರಿಗೆದಾರ",
    "Admin": "ಅಡ್ಮಿನ್",
    "Order": "ಆರ್ಡರ್",
    "Product": "ಉತ್ಪನ್ನ",
    "Quantity": "ಪ್ರಮಾಣ",
    "Price": "ದರ",
    "Total": "ಒಟ್ಟು",
    "Revenue": "ಆದಾಯ",
    "Shipment": "ಸಾರಿಗೆ ಸಾಗಣೆ",
    "Quote": "ಕೋಟೇಶನ್",
    "Vehicle": "ವಾಹನ",
    "Blockchain": "ಬ್ಲಾಕ್‌ಚೇನ್",
    "Hash": "ಹ್ಯಾಶ್",
    "Tx": "ವಹಿವಾಟು"
  },
  ml: {
    "Verify": "വെരിഫൈ ചെയ്യുക",
    "Verified": "വെരിഫൈ ചെയ്തു",
    "Pending": "ബാക്കിയുണ്ട്",
    "Required": "ആവശ്യമാണ്",
    "Optional": "ഓപ്ഷണൽ",
    "Status": "സ്റ്റാറ്റസ്",
    "Document": "രേഖ",
    "Certificate": "സർട്ടിഫിക്കറ്റ്",
    "Upload": "അപ്‌ലോഡ് ചെയ്യുക",
    "Download": "ഡൗൺലോഡ് ചെയ്യുക",
    "Cancel": "റദ്ദാക്കുക",
    "Confirm": "ഉറപ്പാക്കുക",
    "Save": "സേവ് ചെയ്യുക",
    "Edit": "എഡിറ്റ് ചെയ്യുക",
    "Delete": "ഒഴിവാക്കുക",
    "Next": "അടുത്തത്",
    "Back": "മടങ്ങുക",
    "Submit": "സമർപ്പിക്കുക",
    "Search": "തിരയുക",
    "Filter": "ഫിൽട്ടർ",
    "Details": "വിവരങ്ങൾ",
    "Identity": "തിരിച്ചറിയൽ",
    "Organization": "സ്ഥാപനം",
    "Representative": "പ്രതിനിധി",
    "Address": "വിലാസം",
    "Pincode": "പിൻകോഡ്",
    "Mobile": "മൊബൈൽ നമ്പർ",
    "Email": "ഇമെയിൽ",
    "District": "ജില്ല",
    "State": "സംസ്ഥാനം",
    "Village": "ഗ്രാമം",
    "Taluk": "താലൂക്ക്",
    "PATTA": "പട്ടയം",
    "SURVEY": "സർവേ നമ്പർ",
    "BANK": "ബാങ്ക്",
    "ACCOUNT": "അക്കൗണ്ട്",
    "IFSC": "IFSC കോഡ്",
    "PAN": "പാൻ കാർഡ്",
    "Aadhaar": "ആധാർ",
    "Farmer": "കർഷകൻ",
    "Buyer": "വാങ്ങുന്നയാൾ",
    "Transporter": "ഗതാഗതക്കാരൻ",
    "Admin": "അഡ്മിൻ",
    "Order": "ഓർഡർ",
    "Product": "ഉൽപ്പന്നം",
    "Quantity": "അളവ്",
    "Price": "വില",
    "Total": "ആകെ",
    "Revenue": "വരുമാനം",
    "Shipment": "ഷിപ്പ്മെന്റ്",
    "Quote": "ക്വോട്ട്",
    "Vehicle": "വാഹനം",
    "Blockchain": "ബ്ലോക്ക്ചെയിൻ",
    "Hash": "ഹാഷ്",
    "Tx": "ഇടപാട്"
  }
};

function smartTranslate(text, lang) {
  if (!text) return text;
  let translated = text;

  // Check direct dictionary match first
  if (dictionary[lang][text]) return dictionary[lang][text];

  // Pattern translations for common phrases
  const rules = {
    ta: [
      [/^Verify (.*)/i, '$1 சரிபார்க்கவும்'],
      [/^Enter (.*)/i, '$1 உள்ளிடவும்'],
      [/^Upload (.*)/i, '$1 பதிவேற்றவும்'],
      [/^Select (.*)/i, '$1 தேர்ந்தெடுக்கவும்'],
      [/^Invalid (.*)/i, 'செல்லாத $1'],
      [/^Successful (.*)/i, 'வெற்றிகரமான $1'],
      [/^Failed to (.*)/i, '$1 செய்வதில் தோல்வி'],
      [/^No (.*) found/i, '$1 எதுவும் கண்டறியப்படவில்லை'],
      [/^Management/i, 'மேலாண்மை'],
    ],
    hi: [
      [/^Verify (.*)/i, '$1 सत्यापित करें'],
      [/^Enter (.*)/i, '$1 दर्ज करें'],
      [/^Upload (.*)/i, '$1 अपलोड करें'],
      [/^Select (.*)/i, '$1 चुनें'],
      [/^Invalid (.*)/i, 'अमान्य $1'],
      [/^Successful (.*)/i, 'सफल $1'],
      [/^Failed to (.*)/i, '$1 करने में विफल'],
      [/^No (.*) found/i, 'कोई $1 नहीं मिला'],
      [/^Management/i, 'प्रबंधन'],
    ],
    te: [
      [/^Verify (.*)/i, '$1 ధృవీకరించు'],
      [/^Enter (.*)/i, '$1 నమోదు చేయి'],
      [/^Upload (.*)/i, '$1 అప్‌లోడ్ చేయి'],
      [/^Select (.*)/i, '$1 ఎంచుకోండి'],
      [/^Invalid (.*)/i, 'చెల్లని $1'],
      [/^Successful (.*)/i, 'విజయవంతమైన $1'],
      [/^Failed to (.*)/i, '$1 చేయడంలో విఫలమైంది'],
      [/^No (.*) found/i, 'ఏ $1 లభించలేదు'],
      [/^Management/i, 'నిర్వహణ'],
    ],
    kn: [
      [/^Verify (.*)/i, '$1 ದೃಢೀಕರಿಸಿ'],
      [/^Enter (.*)/i, '$1 ನಮೂದಿಸಿ'],
      [/^Upload (.*)/i, '$1 ಅಪ್‌ಲೋಡ್ ಮಾಡಿ'],
      [/^Select (.*)/i, '$1 ಆಯ್ಕೆಮಾಡಿ'],
      [/^Invalid (.*)/i, 'ಅಮಾನ್ಯ $1'],
      [/^Successful (.*)/i, 'ಯಶಸ್ವಿ $1'],
      [/^Failed to (.*)/i, '$1 ಮಾಡಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ'],
      [/^No (.*) found/i, 'ಯಾವುದೇ $1 ಕಂಡುಬಂದಿಲ್ಲ'],
      [/^Management/i, 'ನಿರ್ವಹಣೆ'],
    ],
    ml: [
      [/^Verify (.*)/i, '$1 വെരിഫൈ ചെയ്യുക'],
      [/^Enter (.*)/i, '$1 നൽകുക'],
      [/^Upload (.*)/i, '$1 അപ്‌ലോഡ് ചെയ്യുക'],
      [/^Select (.*)/i, '$1 തിരഞ്ഞെടുക്കുക'],
      [/^Invalid (.*)/i, 'അസാധുവായ $1'],
      [/^Successful (.*)/i, 'വിജയകരമായ $1'],
      [/^Failed to (.*)/i, '$1 ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു'],
      [/^No (.*) found/i, '$1 ഒന്നും കണ്ടെത്തിയില്ല'],
      [/^Management/i, 'മാനേജ്മെന്റ്'],
    ]
  };

  const langRules = rules[lang] || [];
  for (const [regex, repl] of langRules) {
    if (regex.test(translated)) {
      return translated.replace(regex, repl);
    }
  }

  // Word-by-word fallback replace for key terms
  Object.keys(dictionary[lang]).forEach(k => {
    const re = new RegExp(`\\b${k}\\b`, 'g');
    translated = translated.replace(re, dictionary[lang][k]);
  });

  return translated;
}

locales.forEach(l => {
  const filePath = path.join('frontend/src/i18n/locales', l, 'translation.json');
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  Object.keys(untranslatedMap).forEach(keyPath => {
    const enText = untranslatedMap[keyPath].en;
    const translatedText = smartTranslate(enText, l);

    const parts = keyPath.split('.');
    let cur = data;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!cur[parts[i]]) cur[parts[i]] = {};
      cur = cur[parts[i]];
    }
    cur[parts[parts.length - 1]] = translatedText;
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`✓ Updated all ${Object.keys(untranslatedMap).length} remaining keys in ${l}/translation.json`);
});

console.log('✓ Master translation completed for all 6 languages!');
