import fs from 'fs';
import path from 'path';

const untranslatedMap = JSON.parse(fs.readFileSync('scripts/untranslatedMap.json', 'utf8'));
const locales = ['ta', 'hi', 'te', 'kn', 'ml'];

// Comprehensive translation map for specific keys across all sections
const keyTranslations = {
  ta: {
    // farmerVerificationWizard & buyerVerificationWizard
    "fpo": "FPO",
    "farmer": "விவசாயி",
    "failedToLoadVerificationStatus": "சரிபார்ப்பு நிலையை ஏற்ற முடியவில்லை.",
    "pleaseEnterAValid12digitAadhaar": "செல்லுபடியாகும் 12-இலக்க ஆதார் எண்ணை உள்ளிடவும்.",
    "otpSentToYourAadhaarMobile": "உங்கள் ஆதார் மொபைல் எண்ணிற்கு OTP அனுப்பப்பட்டது!",
    "pleaseEnter6digitOtp": "6-இலக்க OTP-ஐ உள்ளிடவும்.",
    "verified_identityVerifiedViaUidaiSandbox": "✓ UIDAI வழியாக அடையாளம் சரிபார்க்கப்பட்டது!",
    "pleaseEnterFarmerIdAndDistrict": "விவசாயி ஐடி மற்றும் மாவட்டத்தை உள்ளிடவும்.",
    "verified_farmerRegistryVerified": "✓ விவசாயி பதிவு சரிபார்க்கப்பட்டது!",
    "pleaseFillAllRequiredLandRecord": "தேவையான நில விவரங்களைப் பூர்த்தி செய்யவும்.",
    "verified_landRecordVerified": "✓ நில ஆவணம் சரிபார்க்கப்பட்டது!",
    "pleaseFillAccountHolderAccountNumber": "கணக்கு வைத்திருப்பவர், கணக்கு எண் மற்றும் IFSC விவரங்களைப் பூர்த்தி செய்யவும்.",
    "accountNumbersDoNotMatch": "கணக்கு எண்கள் பொருந்தவில்லை.",
    "verified_bankAccountVerified": "✓ வங்கி கணக்கு சரிபார்க்கப்பட்டது!",
    "pleaseEnterAValid10characterPan": "செல்லுபடியாகும் 10-எழுத்து பான் எண்ணை உள்ளிடவும்.",
    "verified_panVerifiedSuccessfully": "✓ பான் கார்டு வெற்றிகரமாக சரிபார்க்கப்பட்டது!",
    "pmkisanSkipped": "PM-KISAN தவிர்க்கப்பட்டது.",
    "verified_pmkisanVerified": "✓ PM-KISAN சரிபார்க்கப்பட்டது!",
    "pleaseFillRequiredOrganizationDetails": "அமைப்பின் தேவையான விவரங்களைப் பூர்த்தி செய்யவும்.",
    "verified_organizationIdentityVerified": "✓ அமைப்பின் அடையாளம் சரிபார்க்கப்பட்டது!",
    "pleaseEnterAValid10characterOrganization": "செல்லுபடியாகும் 10-எழுத்து அமைப்பின் பான் எண்ணை உள்ளிடவும்.",
    "verified_organizationPanVerified": "✓ அமைப்பின் பான் கார்டு சரிபார்க்கப்பட்டது!",
    "gstinMarkedAsNotApplicable": "GSTIN பொருந்தாது எனக் குறிக்கப்பட்டது.",
    "verified_gstinVerified": "✓ GSTIN சரிபார்க்கப்பட்டது!",
    "pleaseEnterAValid10digitMobile": "செல்லுபடியாகும் 10-இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
    "otpSentToRepresentativeMobile": "பிரதிநிதியின் மொபைல் எண்ணிற்கு OTP அனுப்பப்பட்டது!",
    "pleaseEnterRepresentativeNameAndDesignation": "பிரதிநிதியின் பெயர் மற்றும் பதவியை உள்ளிடவும்.",
    "verified_authorizedRepresentativeVerified": "✓ அங்கீகரிக்கப்பட்ட பிரதிநிதி சரிபார்க்கப்பட்டார்!",
    "verified_organizationBankAccountVerified": "✓ அமைப்பின் வங்கி கணக்கு சரிபார்க்கப்பட்டது!",
    "pleaseUploadAtLeastRegistrationCertificate": "பதிவுச் சான்றிதழ், பான் மற்றும் வங்கி சான்றுகளைப் பதிவேற்றவும்.",
    "verified_organizationDocumentsVerified": "✓ அமைப்பின் ஆவணங்கள் சரிபார்க்கப்பட்டன!",
    "failedToSkipStep": "படியைத் தவிர்க்க முடியவில்லை.",
    "progressSavedReturningToDashboard": "முன்னேற்றம் சேமிக்கப்பட்டது. டாஷ்போர்டிற்குத் திரும்புகிறது.",
    "verificationSummary": "சரிபார்ப்பு சுருக்கம்",
    "reviewYourOverallVerificationStatusAnd": "உங்கள் ஒட்டுமொத்த சரிபார்ப்பு நிலையை மதிப்பாய்வு செய்யவும்.",
    "verified": "சரிபார்க்கப்பட்டது",
    "pending": "நிலுவையில் உள்ளது",
    "officialIdentityComplianceGateway": "அதிகாரப்பூர்வ அடையாள வாயில்",
    "saveExitToDashboard": "சேமித்து டாஷ்போர்டிற்குச் செல்",
    "mandatoryVerification": "கட்டாயச் சரிபார்ப்பு",
    "optionalVerification": "விருப்பச் சரிபார்ப்பு",
    "aadhaarAuthenticationProtocol": "ஆதார் அங்கீகார நெறிமுறை",
    "enterYour12digitAadhaarNumberTo": "UIDAI போர்ட்டல் மூலம் OTP பெற 12-இலக்க ஆதார் எண்ணை உள்ளிடவும்.",
    "enter12digitAadhaarNumber": "12-இலக்க ஆதார் எண்ணை உள்ளிடவும்",
    "sendAadhaarOtp": "ஆதார் OTP அனுப்பு",
    "enter6digitOtp_req": "6-இலக்க OTP உள்ளிடுக *",
    "verifyContinue": "சரிபார்த்து தொடரவும்",
    "saveExit": "சேமித்து வெளியேறு",
    "skipStep": "படியைத் தவிர்க்கவும்",
    "nextStep": "அடுத்த படி",
    "farmerDatabaseProtocol": "விவசாயி தரவுத்தள நெறிமுறை",
    "enterYourOfficialFarmerAgristackId": "பதிவு நிலையை சரிபார்க்க உங்கள் விவசாயி ஐடியை உள்ளிடவும்.",
    "farmerId": "விவசாயி ஐடி",
    "location": "அமைவிடம்",
    "farmerIdAgristackId_req": "விவசாயி ஐடி / அக்ரிஸ்டாக் ஐடி *",
    "state_req": "மாநிலம் *",
    "district_req": "மாவட்டம் *",
    "back": "பின்னால்",
    "landHoldingProtocol": "நில உடைமை நெறிமுறை",
    "enterStateDistrictTalukVillagePatta": "மாநிலம், மாவட்டம், தாலுகா, கிராமம், பட்டா மற்றும் சர்வே எண்களை உள்ளிடவும்.",
    "patta712No": "பட்டா / 7-12 எண்",
    "surveyNo": "சர்வே எண்",
    "extent": "பரப்பளவு",
    "taluk_req": "தாலுகா *",
    "village_req": "கிராமம் *",
    "pattaKhataNo_req": "பட்டா / கதா எண் *",
    "surveyNo_req": "சர்வே எண் *",
    "landExtentAcres_req": "நிலப் பரப்பளவு (ஏக்கர்) *",
    "landType": "நிலத்தின் வகை",
    "irrigatedWet": "நஞ்சை / பாசன நிலம்",
    "dryRainfed": "புஞ்சை / மானாவாரி",
    "horticulture": "தோட்டக்கலை",
    "uploadPattaLandRecordDocument_req": "பட்டா / நில ஆவணத்தைப் பதிவேற்றவும் *",
    "uploadPdfJpgOrPngCopy": "பட்டா அல்லது நில ஆவண நகலை பதிவேற்றவும் (அதிகபட்சம் 5MB)",
    "bankSettlementProtocol": "வங்கி பணப்பரிமாற்ற நெறிமுறை",
    "linkYourActiveBankAccountFor": "நேரடி செலுத்துதல்களுக்கு உங்கள் வங்கி கணக்கை இணைக்கவும்.",
    "accountHolder": "கணக்கு வைத்திருப்பவர்",
    "bankName": "வங்கியின் பெயர்",
    "accountNo": "கணக்கு எண்",
    "accountHolderName_req": "கணக்கு வைத்திருப்பவர் பெயர் *",
    "asPerBankPassbook": "வங்கி பாஸ்புக்கில் உள்ளபடி",
    "bankName_req": "வங்கியின் பெயர் *",
    "branchName": "கிளை பெயர்",
    "accountNumber_req": "கணக்கு எண் *",
    "enterAccountNumber": "கணக்கு எண்ணை உள்ளிடவும்",
    "confirmAccountNumber_req": "கணக்கு எண்ணை உறுதிப்படுத்தவும் *",
    "reenterAccountNumber": "கணக்கு எண்ணை மீண்டும் உள்ளிடவும்",
    "ifscCode_req": "IFSC குறியீடு *",
    "uploadBankPassbookCancelledCheque_req": "வங்கி பாஸ்புக் / காசோலை பதிவேற்றம் *",
    "uploadFrontPageOfPassbookOr": "பாஸ்புக்கின் முதல் பக்கம் அல்லது ரத்து செய்யப்பட்ட காசோலையைப் பதிவேற்றவும்",
    "panVerificationProtocol": "பான் கார்டு சரிபார்ப்பு நெறிமுறை",
    "enterYour10characterPermanentAccountNumber": "வரி இணக்கத்திற்காக பான் எண்ணை உள்ளிடவும்.",
    "panNumber": "பான் எண்",
    "matchStatus": "பொருந்தும் நிலை",
    "panNumber_req": "பான் எண் *",
    "nameAsPerPanOptional": "பான் கார்டில் உள்ள பெயர்",
    "fullNameAsPrintedOnPan": "பான் கார்டில் அச்சிடப்பட்ட முழு பெயர்",
    "uploadPanCardCopy_req": "பான் கார்டு நகலைப் பதிவேற்றவும் *",
    "clearFrontScanOrPhotoOf": "பான் கார்டின் தெளிவான புகைப்படத்தைப் பதிவேற்றவும்",
    "pmkisanSchemeProtocol": "PM-KISAN திட்ட நெறிமுறை",
    "optionallyLinkPmkisanBeneficiaryReferenceFor": "கூடுதல் நம்பிக்கைக்கு PM-KISAN குறிப்பு எண்ணை இணைக்கவும்.",
    "pmkisanRegistrationBeneficiaryReference": "PM-KISAN பதிவு / பயனாளியின் குறிப்பு எண்",
    "verifyPmkisanContinue": "PM-KISAN சரிபார்த்து தொடரவும்",
    "viewSummary": "சுருக்கத்தைக் காண்க",
    "organizationRegistrationProtocol": "அமைப்பின் பதிவு நெறிமுறை",
    "verifyOfficialFpoFpcCooperativeEntity": "அமைப்பின் அதிகாரப்பூர்வ பதிவு விவரங்களைச் சரிபார்க்கவும்.",
    "legalName": "சட்டப்பூர்வ பெயர்",
    "registrationNo": "பதிவு எண்",
    "organizationLegalName_req": "அமைப்பின் சட்டப்பூர்வ பெயர் *",
    "organizationType_req": "அமைப்பின் வகை *",
    "fpoFpcProducerCompany": "FPO / FPC (உற்பத்தியாளர் நிறுவனம்)",
    "agriculturalCooperativeSociety": "விவசாய கூட்டுறவு சங்கம்",
    "farmerShgPartnership": "விவசாய சுயஉதவிக்குழு / கூட்டாண்மை",
    "registrationCinNumber_req": "பதிவு / CIN எண் *",
    "pincode_req": "அஞ்சல் குறியீடு *",
    "registeredOfficeAddress_req": "பதிவு செய்யப்பட்ட அலுவலக முகவரி *",
    "fullAddressOfOrganizationOffice": "அலுவலகத்தின் முழு முகவரி",
    "organizationPanProtocol": "அமைப்பின் பான் கார்டு நெறிமுறை",
    "enterPermanentAccountNumberIssuedIn": "அமைப்பின் சட்டப்பூர்வ பெயரிலுள்ள பான் எண்ணை உள்ளிடவும்.",
    "orgPan": "அமைப்பின் பான்",
    "organizationPan_req": "அமைப்பின் பான் எண் *",
    "gstinRegistrationProtocol": "GSTIN பதிவு நெறிமுறை",
    "provide15characterGstinRegistrationIfRegistered": "ஜிஎஸ்டி பதிவு எண் இருந்தால் வழங்கவும்.",
    "notApplicable": "பொருந்தாது",
    "verifyGstin": "GSTIN சரிபார்க்கவும்",
    "authorizedOfficialProtocol": "அங்கீகரிக்கப்பட்ட அதிகாரி நெறிமுறை",
    "verifyIdentityAndMobileAuthorizationOf": "பிரதிநிதியின் அடையாளம் மற்றும் மொபைல் அங்கீகாரத்தைச் சரிபார்க்கவும்.",
    "representativeName_req": "பிரதிநிதியின் பெயர் *",
    "designation_req": "பதவி *",
    "representativeMobileNumber_req": "பிரதிநிதியின் மொபைல் எண் *",
    "enter10digitMobileNumber": "10-இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    "sendRepresentativeOtp": "பிரதிநிதி OTP அனுப்பு",
    "verifyRepresentative": "பிரதிநிதியைச் சரிபார்க்கவும்",
    "organizationSettlementAccountProtocol": "அமைப்பின் கணக்கு நெறிமுறை",
    "linkPrimarySettlementBankAccountOf": "நேரடிப் பரிமாற்றத்திற்காக அமைப்பின் வங்கி கணக்கை இணைக்கவும்.",
    "exactLegalNameAsPerBank": "வங்கி அறிக்கையில் உள்ள சட்டப்பூர்வ பெயர்",
    "enterBankAccountNumber": "வங்கி கணக்கு எண்ணை உள்ளிடவும்",
    "organizationDocumentDossier": "அமைப்பின் ஆவணங்கள்",
    "uploadMandatoryRegistrationTaxBankProof": "தேவையான பதிவு, வரி மற்றும் வங்கி சான்றுகளைப் பதிவேற்றவும்.",
    "1OrganizationRegistrationCertificate_req": "1. அமைப்பின் பதிவுச் சான்றிதழ் *",
    "2OrganizationPanCardCopy_req": "2. அமைப்பின் பான் கார்டு நகல் *",
    "3BankPassbookCancelledCheque_req": "3. வங்கி பாஸ்புக் / காசோலை *",
    "4AuthorizationLetterBoardResolution": "4. அங்கீகாரக் கடிதம் / தீர்மானம்",
    "5GstCertificateIfApplicable": "5. ஜிஎஸ்டி சான்றிதழ் (பொருந்தினால்)",
    "submitDocumentsProceed": "ஆவணங்களைச் சமர்ப்பித்து தொடரவும்",
    "backToReview": "மதிப்பாய்வுக்குத் திரும்பு",
    "returnToDashboard": "டாஷ்போர்டிற்குத் திரும்பு",
    "yourInformationIsSecurelyProcessedSensitive": "உங்கள் தகவல்கள் பாதுகாப்பாக கையாளப்படுகின்றன."
  },
  hi: {
    "fpo": "FPO",
    "farmer": "किसान",
    "failedToLoadVerificationStatus": "सत्यापन स्थिति लोड करने में विफल।",
    "pleaseEnterAValid12digitAadhaar": "कृपया 12 अंकों का वैध आधार नंबर दर्ज करें।",
    "otpSentToYourAadhaarMobile": "आपके आधार पंजीकृत मोबाइल पर OTP भेजा गया!",
    "pleaseEnter6digitOtp": "कृपया 6 अंकों का OTP दर्ज करें।",
    "verified_identityVerifiedViaUidaiSandbox": "✓ UIDAI द्वारा पहचान सत्यापित!",
    "pleaseEnterFarmerIdAndDistrict": "कृपया किसान आईडी और जिला दर्ज करें।",
    "verified_farmerRegistryVerified": "✓ किसान रजिस्ट्री सत्यापित!",
    "pleaseFillAllRequiredLandRecord": "कृपया आवश्यक भूमि विवरण भरें।",
    "verified_landRecordVerified": "✓ भूमि रिकॉर्ड सत्यापित!",
    "pleaseFillAccountHolderAccountNumber": "कृपया खाताधारक का नाम, खाता संख्या और IFSC भरें।",
    "accountNumbersDoNotMatch": "खाता संख्या मेल नहीं खाती।",
    "verified_bankAccountVerified": "✓ बैंक खाता सत्यापित!",
    "pleaseEnterAValid10characterPan": "कृपया 10 अक्षरों का वैध पैन दर्ज करें।",
    "verified_panVerifiedSuccessfully": "✓ पैन सफलतापूर्वक सत्यापित!",
    "pmkisanSkipped": "PM-KISAN छोड़ा गया।",
    "verified_pmkisanVerified": "✓ PM-KISAN सत्यापित!",
    "pleaseFillRequiredOrganizationDetails": "कृपया आवश्यक संगठन विवरण भरें।",
    "verified_organizationIdentityVerified": "✓ संगठन पहचान सत्यापित!",
    "pleaseEnterAValid10characterOrganization": "कृपया संगठन का वैध पैन दर्ज करें।",
    "verified_organizationPanVerified": "✓ संगठन पैन सत्यापित!",
    "gstinMarkedAsNotApplicable": "GSTIN लागू नहीं के रूप में चिह्नित।",
    "verified_gstinVerified": "✓ GSTIN सत्यापित!",
    "pleaseEnterAValid10digitMobile": "कृपया 10 अंकों का वैध मोबाइल नंबर दर्ज करें।",
    "otpSentToRepresentativeMobile": "प्रतिनिधि के मोबाइल पर OTP भेजा गया!",
    "pleaseEnterRepresentativeNameAndDesignation": "कृपया प्रतिनिधि का नाम और पद दर्ज करें।",
    "verified_authorizedRepresentativeVerified": "✓ अधिकृत प्रतिनिधि सत्यापित!",
    "verified_organizationBankAccountVerified": "✓ संगठन बैंक खाता सत्यापित!",
    "pleaseUploadAtLeastRegistrationCertificate": "कृपया पंजीकरण प्रमाण पत्र, पैन और बैंक प्रमाण अपलोड करें।",
    "verified_organizationDocumentsVerified": "✓ संगठन दस्तावेज़ सत्यापित!",
    "failedToSkipStep": "चरण छोड़ने में विफल।",
    "progressSavedReturningToDashboard": "प्रगति सहेजी गई। डैशबोर्ड पर लौट रहे हैं।",
    "verificationSummary": "सत्यापन सारांश",
    "reviewYourOverallVerificationStatusAnd": "अपनी समग्र सत्यापन स्थिति की समीक्षा करें।",
    "verified": "सत्यापित",
    "pending": "लंबित",
    "officialIdentityComplianceGateway": "आधिकारिक पहचान पोर्टल",
    "saveExitToDashboard": "सहेजें और डैशबोर्ड पर जाएं",
    "mandatoryVerification": "अनिवार्य सत्यापन",
    "optionalVerification": "वैकल्पिक सत्यापन",
    "aadhaarAuthenticationProtocol": "आधार प्रमाणीकरण तंत्र",
    "enterYour12digitAadhaarNumberTo": "OTP प्राप्त करने के लिए अपना 12 अंकों का आधार दर्ज करें।",
    "enter12digitAadhaarNumber": "12 अंकों का आधार नंबर दर्ज करें",
    "sendAadhaarOtp": "आधार OTP भेजें",
    "enter6digitOtp_req": "6 अंकों का OTP दर्ज करें *",
    "verifyContinue": "सत्यापित करें और आगे बढ़ें",
    "saveExit": "सहेजें और बाहर निकलें",
    "skipStep": "चरण छोड़ें",
    "nextStep": "अगला चरण",
    "farmerDatabaseProtocol": "किसान डेटाबेस प्रोटोकॉल",
    "enterYourOfficialFarmerAgristackId": "अपनी किसान आईडी दर्ज करें।",
    "farmerId": "किसान आईडी",
    "location": "स्थान",
    "farmerIdAgristackId_req": "किसान आईडी / एग्रीस्टैक आईडी *",
    "state_req": "राज्य *",
    "district_req": "जिला *",
    "back": "पीछे",
    "landHoldingProtocol": "भूमि जोत प्रोटोकॉल",
    "enterStateDistrictTalukVillagePatta": "राज्य, जिला, तालुका, गांव और खसरा/पट्टा नंबर दर्ज करें।",
    "patta712No": "पट्टा / 7-12 नंबर",
    "surveyNo": "सर्वे नंबर",
    "extent": "क्षेत्रफल",
    "taluk_req": "तालुका *",
    "village_req": "गांव *",
    "pattaKhataNo_req": "पट्टा / खाता नंबर *",
    "surveyNo_req": "सर्वे नंबर *",
    "landExtentAcres_req": "भूमि क्षेत्रफल (एकड़) *",
    "landType": "भूमि का प्रकार",
    "irrigatedWet": "सिंचित / नम",
    "dryRainfed": "शुष्क / असिंचित",
    "horticulture": "बागवानी",
    "uploadPattaLandRecordDocument_req": "पट्टा / भूमि दस्तावेज़ अपलोड करें *",
    "uploadPdfJpgOrPngCopy": "7/12 या पट्टा की प्रति अपलोड करें (अधिकतम 5MB)",
    "bankSettlementProtocol": "बैंक सेटलमेंट प्रोटोकॉल",
    "linkYourActiveBankAccountFor": "भुगतान प्राप्त करने के लिए अपना बैंक खाता जोड़ें।",
    "accountHolder": "खाताधारक",
    "bankName": "बैंक का नाम",
    "accountNo": "खाता संख्या",
    "accountHolderName_req": "खाताधारक का नाम *",
    "asPerBankPassbook": "पासबुक के अनुसार",
    "bankName_req": "बैंक का नाम *",
    "branchName": "शाखा का नाम",
    "accountNumber_req": "खाता संख्या *",
    "enterAccountNumber": "खाता संख्या दर्ज करें",
    "confirmAccountNumber_req": "खाता संख्या की पुष्टि करें *",
    "reenterAccountNumber": "खाता संख्या पुनः दर्ज करें",
    "ifscCode_req": "IFSC कोड *",
    "uploadBankPassbookCancelledCheque_req": "पासबुक / रद्द चेक अपलोड करें *",
    "uploadFrontPageOfPassbookOr": "पासबुक का मुख्य पृष्ठ या रद्द चेक अपलोड करें",
    "panVerificationProtocol": "पैन सत्यापन प्रोटोकॉल",
    "enterYour10characterPermanentAccountNumber": "कर अनुपालन के लिए पैन दर्ज करें।",
    "panNumber": "पैन नंबर",
    "matchStatus": "मिलान स्थिति",
    "panNumber_req": "पैन नंबर *",
    "nameAsPerPanOptional": "पैन के अनुसार नाम",
    "fullNameAsPrintedOnPan": "पैन कार्ड पर छपा पूरा नाम",
    "uploadPanCardCopy_req": "पैन कार्ड की प्रति अपलोड करें *",
    "clearFrontScanOrPhotoOf": "पैन कार्ड की स्पष्ट तस्वीर अपलोड करें",
    "pmkisanSchemeProtocol": "पीएम-किसान योजना",
    "optionallyLinkPmkisanBeneficiaryReferenceFor": "अतिरिक्त विश्वसनीयता के लिए पीएम-किसान संदर्भ नंबर जोड़ें।",
    "pmkisanRegistrationBeneficiaryReference": "पीएम-किसान पंजीकरण नंबर",
    "verifyPmkisanContinue": "पीएम-किसान सत्यापित करें और आगे बढ़ें",
    "viewSummary": "सारांश देखें",
    "organizationRegistrationProtocol": "संगठन पंजीकरण",
    "verifyOfficialFpoFpcCooperativeEntity": "संगठन के पंजीकरण विवरण सत्यापित करें।",
    "legalName": "कानूनी नाम",
    "registrationNo": "पंजीकरण संख्या",
    "organizationLegalName_req": "संगठन का कानूनी नाम *",
    "organizationType_req": "संगठन का प्रकार *",
    "fpoFpcProducerCompany": "FPO / FPC (उत्पादक कंपनी)",
    "agriculturalCooperativeSociety": "कृषि सहकारी समिति",
    "farmerShgPartnership": "किसान स्वयं सहायता समूह",
    "registrationCinNumber_req": "पंजीकरण / CIN नंबर *",
    "pincode_req": "पिनकोड *",
    "registeredOfficeAddress_req": "पंजीकृत कार्यालय का पता *",
    "fullAddressOfOrganizationOffice": "कार्यालय का पूरा पता",
    "organizationPanProtocol": "संगठन पैन प्रोटोकॉल",
    "enterPermanentAccountNumberIssuedIn": "संगठन के नाम पर जारी पैन नंबर दर्ज करें।",
    "orgPan": "संगठन पैन",
    "organizationPan_req": "संगठन का पैन नंबर *",
    "gstinRegistrationProtocol": "GSTIN पंजीकरण",
    "provide15characterGstinRegistrationIfRegistered": "यदि पंजीकृत हैं तो 15 अक्षरों का GSTIN दर्ज करें।",
    "notApplicable": "लागू नहीं",
    "verifyGstin": "GSTIN सत्यापित करें",
    "authorizedOfficialProtocol": "अधिकृत अधिकारी",
    "verifyIdentityAndMobileAuthorizationOf": "प्रतिनिधि की पहचान और मोबाइल सत्यापित करें।",
    "representativeName_req": "प्रतिनिधि का नाम *",
    "designation_req": "पद *",
    "representativeMobileNumber_req": "प्रतिनिधि का मोबाइल नंबर *",
    "enter10digitMobileNumber": "10 अंकों का मोबाइल नंबर दर्ज करें",
    "sendRepresentativeOtp": "प्रतिनिधि OTP भेजें",
    "verifyRepresentative": "प्रतिनिधि सत्यापित करें",
    "organizationSettlementAccountProtocol": "संगठन बैंक खाता",
    "linkPrimarySettlementBankAccountOf": "सीधा भुगतान प्राप्त करने के लिए संगठन का बैंक खाता जोड़ें।",
    "exactLegalNameAsPerBank": "बैंक में दर्ज सही नाम",
    "enterBankAccountNumber": "बैंक खाता संख्या दर्ज करें",
    "organizationDocumentDossier": "संगठन दस्तावेज़",
    "uploadMandatoryRegistrationTaxBankProof": "आवश्यक पंजीकरण और बैंक प्रमाण अपलोड करें।",
    "1OrganizationRegistrationCertificate_req": "1. संगठन का पंजीकरण प्रमाण पत्र *",
    "2OrganizationPanCardCopy_req": "2. संगठन के पैन कार्ड की प्रति *",
    "3BankPassbookCancelledCheque_req": "3. बैंक पासबुक / रद्द चेक *",
    "4AuthorizationLetterBoardResolution": "4. प्राधिकरण पत्र / प्रस्ताव",
    "5GstCertificateIfApplicable": "5. जीएसटी प्रमाण पत्र (यदि लागू हो)",
    "submitDocumentsProceed": "दस्तावेज़ जमा करें और आगे बढ़ें",
    "backToReview": "समीक्षा पर लौटें",
    "returnToDashboard": "डैशबोर्ड पर लौटें",
    "yourInformationIsSecurelyProcessedSensitive": "आपकी जानकारी सुरक्षित रूप से संसाधित की जाती है।"
  },
  te: {
    "fpo": "FPO",
    "farmer": "రైతు",
    "failedToLoadVerificationStatus": "పరిశీలన స్థితిని లోడ్ చేయడంలో విఫలమైంది.",
    "pleaseEnterAValid12digitAadhaar": "దయచేసి చెల్లుబాటు అయ్యే 12 అంకెల ఆధార్ సంఖ్యను నమోదు చేయండి.",
    "otpSentToYourAadhaarMobile": "మీ ఆధార్ మొబైల్‌కు OTP పంపబడింది!",
    "pleaseEnter6digitOtp": "దయచేసి 6 అంకెల OTP నమోదు చేయండి.",
    "verified_identityVerifiedViaUidaiSandbox": "✓ UIDAI ద్వారా గుర్తింపు ధృవీకరించబడింది!",
    "pleaseEnterFarmerIdAndDistrict": "దయచేసి రైతు ఐడీ మరియు జిల్లా నమోదు చేయండి.",
    "verified_farmerRegistryVerified": "✓ రైతు రిజిస్ట్రీ ధృవీకరించబడింది!",
    "pleaseFillAllRequiredLandRecord": "దయచేసి భూమి వివరాలను భర్తీ చేయండి.",
    "verified_landRecordVerified": "✓ భూమి రికార్డు ధృవీకరించబడింది!",
    "pleaseFillAccountHolderAccountNumber": "దయచేసి ఖాతాదారుని పేరు, ఖాతా సంఖ్య మరియు IFSC భర్తీ చేయండి.",
    "accountNumbersDoNotMatch": "ఖాతా సంఖ్యలు సరిపోలలేదు.",
    "verified_bankAccountVerified": "✓ బ్యాంక్ ఖాతా ధృవీకరించబడింది!",
    "pleaseEnterAValid10characterPan": "దయచేసి చెల్లుబాటు అయ్యే 10 అక్షరాల పాన్ నమోదు చేయండి.",
    "verified_panVerifiedSuccessfully": "✓ పాన్ విజయవంతంగా ధృవీకరించబడింది!",
    "pmkisanSkipped": "PM-KISAN దాటవేయబడింది.",
    "verified_pmkisanVerified": "✓ PM-KISAN ధృవీకరించబడింది!",
    "pleaseFillRequiredOrganizationDetails": "దయచేసి సంస్థ వివరాలను భర్తీ చేయండి.",
    "verified_organizationIdentityVerified": "✓ సంస్థ గుర్తింపు ధృవీకరించబడింది!",
    "pleaseEnterAValid10characterOrganization": "దయచేసి సంస్థ యొక్క పాన్ నమోదు చేయండి.",
    "verified_organizationPanVerified": "✓ సంస్థ పాన్ ధృవీకరించబడింది!",
    "gstinMarkedAsNotApplicable": "GSTIN వర్తించదని గుర్తించబడింది.",
    "verified_gstinVerified": "✓ GSTIN ధృవీకరించబడింది!",
    "pleaseEnterAValid10digitMobile": "దయచేసి 10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి.",
    "otpSentToRepresentativeMobile": "ప్రతినిధి మొబైల్‌కు OTP పంపబడింది!",
    "pleaseEnterRepresentativeNameAndDesignation": "దయచేసి ప్రతినిధి పేరు మరియు హోదా నమోదు చేయండి.",
    "verified_authorizedRepresentativeVerified": "✓ అధికారిక ప్రతినిధి ధృవీకరించబడ్డారు!",
    "verified_organizationBankAccountVerified": "✓ సంస్థ బ్యాంక్ ఖాతా ధృవీకరించబడింది!",
    "pleaseUploadAtLeastRegistrationCertificate": "దయచేసి రిజిస్ట్రేషన్ పత్రం, పాన్ మరియు బ్యాంక్ పత్రాలను అప్‌లోడ్ చేయండి.",
    "verified_organizationDocumentsVerified": "✓ సంస్థ పత్రాలు ధృవీకరించబడ్డాయి!",
    "failedToSkipStep": "దశను దాటవేయడంలో విఫలమైంది.",
    "progressSavedReturningToDashboard": "పురోగతి సేవ్ చేయబడింది. డాష్‌బోర్డ్‌కు తిరిగి వెళుతున్నారు.",
    "verificationSummary": "ధృవీకరణ సారాంశం",
    "reviewYourOverallVerificationStatusAnd": "మీ మొత్తం ధృవీకరణ స్థితిని పునఃపరిశీలించండి.",
    "verified": "ధృవీకరించబడింది",
    "pending": "పెండింగ్",
    "officialIdentityComplianceGateway": "అధికారిక గుర్తింపు పోర్టల్",
    "saveExitToDashboard": "సేవ్ చేసి డాష్‌బోర్డ్‌కు వెళ్లండి",
    "mandatoryVerification": "తప్పనిసరి ధృవీకరణ",
    "optionalVerification": "ఐచ్ఛిక ధృవీకరణ",
    "aadhaarAuthenticationProtocol": "ఆధార్ పరిశీలన విధానం",
    "enterYour12digitAadhaarNumberTo": "OTP పొందడానికి 12 అంకెల ఆధార్ సంఖ్యను నమోదు చేయండి.",
    "enter12digitAadhaarNumber": "12 అంకెల ఆధార్ సంఖ్యను నమోదు చేయండి",
    "sendAadhaarOtp": "ఆధార్ OTP పంపు",
    "enter6digitOtp_req": "6 అంకెల OTP నమోదు చేయండి *",
    "verifyContinue": "ధృవీకరించి కొనసాగండి",
    "saveExit": "సేవ్ చేసి నిష్క్రమించు",
    "skipStep": "దశను దాటవేయి",
    "nextStep": "తరువాతి దశ",
    "farmerDatabaseProtocol": "రైతు డేటాబేస్ విధానం",
    "enterYourOfficialFarmerAgristackId": "మీ రైతు ఐడీ నమోదు చేయండి.",
    "farmerId": "రైతు ఐడీ",
    "location": "ప్రాంతం",
    "farmerIdAgristackId_req": "రైతు ఐడీ / అగ్రిస్టాక్ ఐడీ *",
    "state_req": "రాష్ట్రం *",
    "district_req": "జిల్లా *",
    "back": "వెనుకకు",
    "landHoldingProtocol": "భూమి వివరాలు",
    "enterStateDistrictTalukVillagePatta": "రాష్ట్రం, జిల్లా, తాలూకా, గ్రామం మరియు పట్టా సంఖ్యలను నమోదు చేయండి.",
    "patta712No": "పట్టా సంఖ్య",
    "surveyNo": "సర్వే సంఖ్య",
    "extent": "విస్తీర్ణం",
    "taluk_req": "తాలూకా *",
    "village_req": "గ్రామం *",
    "pattaKhataNo_req": "పట్టా / ఖాతా సంఖ్య *",
    "surveyNo_req": "సర్వే సంఖ్య *",
    "landExtentAcres_req": "భూమి విస్తీర్ణం (ఎకరాలు) *",
    "landType": "భూమి రకం",
    "irrigatedWet": "మాగాణి / నీటిపారుదల",
    "dryRainfed": "మెట్ట / వర్షాధార",
    "horticulture": "తోటపని",
    "uploadPattaLandRecordDocument_req": "పట్టా / భూమి పత్రాన్ని అప్‌లోడ్ చేయండి *",
    "uploadPdfJpgOrPngCopy": "పట్టా పత్రం ప్రతిని అప్‌లోడ్ చేయండి",
    "bankSettlementProtocol": "బ్యాంక్ ఖాతా అనుసంధానం",
    "linkYourActiveBankAccountFor": "చెల్లింపులు పొందడానికి బ్యాంక్ ఖాతాను జోడించండి.",
    "accountHolder": "ఖాతాదారు",
    "bankName": "బ్యాంక్ పేరు",
    "accountNo": "ఖాతా సంఖ్య",
    "accountHolderName_req": "ఖాతాదారుని పేరు *",
    "asPerBankPassbook": "పాస్‌బుక్ ప్రకారం",
    "bankName_req": "బ్యాంక్ పేరు *",
    "branchName": "బ్రాంచ్ పేరు",
    "accountNumber_req": "ఖాతా సంఖ్య *",
    "enterAccountNumber": "ఖాతా సంఖ్యను నమోదు చేయండి",
    "confirmAccountNumber_req": "ఖాతా సంఖ్యను స్థిరీకరించండి *",
    "reenterAccountNumber": "ఖాతా సంఖ్యను మళ్లీ నమోదు చేయండి",
    "ifscCode_req": "IFSC కోడ్ *",
    "uploadBankPassbookCancelledCheque_req": "పాస్‌బుక్ / చెక్కు అప్‌లోడ్ చేయండి *",
    "uploadFrontPageOfPassbookOr": "పాస్‌బుక్ మొదటి పేజీ లేదా రద్దు చేసిన చెక్కును అప్‌లోడ్ చేయండి",
    "panVerificationProtocol": "పాన్ కార్డ్ ధృవీకరణ",
    "enterYour10characterPermanentAccountNumber": "పాన్ సంఖ్యను నమోదు చేయండి.",
    "panNumber": "పాన్ సంఖ్య",
    "matchStatus": "పోలిక స్థితి",
    "panNumber_req": "పాన్ సంఖ్య *",
    "nameAsPerPanOptional": "పాన్ లో ఉన్న పేరు",
    "fullNameAsPrintedOnPan": "పాన్ కార్డ్‌లో ఉన్న పూర్తి పేరు",
    "uploadPanCardCopy_req": "పాన్ కార్డ్ ప్రతిని అప్‌లోడ్ చేయండి *",
    "clearFrontScanOrPhotoOf": "పాన్ కార్డ్ స్పష్టమైన చిత్రాన్ని అప్‌లోడ్ చేయండి",
    "pmkisanSchemeProtocol": "పీఎం-కిసాన్ పథకం",
    "optionallyLinkPmkisanBeneficiaryReferenceFor": "నమ్మకం కోసం పీఎం-కిసాన్ సంఖ్యను జోడించండి.",
    "pmkisanRegistrationBeneficiaryReference": "పీఎం-కిసాన్ నమోదు సంఖ్య",
    "verifyPmkisanContinue": "పీఎం-కిసాన్ ధృవీకరించి కొనసాగండి",
    "viewSummary": "సారాంశం చూడండి",
    "organizationRegistrationProtocol": "సంస్థ నమోదు",
    "verifyOfficialFpoFpcCooperativeEntity": "సంస్థ నమోదు వివరాలను పరిశీలించండి.",
    "legalName": "చట్టబద్ధమైన పేరు",
    "registrationNo": "రిజిస్ట్రేషన్ సంఖ్య",
    "organizationLegalName_req": "సంస్థ చట్టబద్ధమైన పేరు *",
    "organizationType_req": "సంస్థ రకం *",
    "fpoFpcProducerCompany": "FPO / FPC (రైతు ఉత్పత్తి కంపెనీ)",
    "agriculturalCooperativeSociety": "వ్యవసాయ సహకార సంఘం",
    "farmerShgPartnership": "రైతు స్వయం సహాయక సంఘం",
    "registrationCinNumber_req": "రిజిస్ట్రేషన్ / CIN సంఖ్య *",
    "pincode_req": "పిన్‌కోడ్ *",
    "registeredOfficeAddress_req": "రిజిస్టర్డ్ ఆఫీస్ చిరునామా *",
    "fullAddressOfOrganizationOffice": "కార్యాలయం పూర్తి చిరునామా",
    "organizationPanProtocol": "సంస్థ పాన్ వివరాలు",
    "enterPermanentAccountNumberIssuedIn": "సంస్థ పేరుపై ఉన్న పాన్ నమోదు చేయండి.",
    "orgPan": "సంస్థ పాన్",
    "organizationPan_req": "సంస్థ పాన్ సంఖ్య *",
    "gstinRegistrationProtocol": "GSTIN రిజిస్ట్రేషన్",
    "provide15characterGstinRegistrationIfRegistered": "జీఎస్టీ సంఖ్య ఉన్నట్లయితే నమోదు చేయండి.",
    "notApplicable": "వర్తించదు",
    "verifyGstin": "GSTIN ధృవీకరించు",
    "authorizedOfficialProtocol": "అధికారిక ప్రతినిధి",
    "verifyIdentityAndMobileAuthorizationOf": "ప్రతినిధి గుర్తింపు మరియు మొబైల్ పరిశీలించండి.",
    "representativeName_req": "ప్రతినిధి పేరు *",
    "designation_req": "హోదా *",
    "representativeMobileNumber_req": "ప్రతినిధి మొబైల్ సంఖ్య *",
    "enter10digitMobileNumber": "10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి",
    "sendRepresentativeOtp": "ప్రతినిధి OTP పంపు",
    "verifyRepresentative": "ప్రతినిధిని ధృవీకరించు",
    "organizationSettlementAccountProtocol": "సంస్థ బ్యాంక్ ఖాతా",
    "linkPrimarySettlementBankAccountOf": "నేరుగా చెల్లింపులు పొందడానికి సంస్థ బ్యాంక్ ఖాతాను జోడించండి.",
    "exactLegalNameAsPerBank": "బ్యాంక్‌లో ఉన్న సరైన పేరు",
    "enterBankAccountNumber": "బ్యాంక్ ఖాతా సంఖ్యను నమోదు చేయండి",
    "organizationDocumentDossier": "సంస్థ పత్రాలు",
    "uploadMandatoryRegistrationTaxBankProof": "అవసరమైన రిజిస్ట్రేషన్ మరియు బ్యాంక్ పత్రాలను అప్‌లోడ్ చేయండి.",
    "1OrganizationRegistrationCertificate_req": "1. సంస్థ రిజిస్ట్రేషన్ పత్రం *",
    "2OrganizationPanCardCopy_req": "2. సంస్థ పాన్ కార్డ్ ప్రతి *",
    "3BankPassbookCancelledCheque_req": "3. బ్యాంక్ పాస్‌బుక్ / చెక్కు *",
    "4AuthorizationLetterBoardResolution": "4. అధికార పత్రం / తీర్మానం",
    "5GstCertificateIfApplicable": "5. జీఎస్టీ పత్రం (వర్తిస్తే)",
    "submitDocumentsProceed": "పత్రాలను సమర్పించి కొనసాగండి",
    "backToReview": "సమీక్షకు తిరిగి వెళ్లండి",
    "returnToDashboard": "డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
    "yourInformationIsSecurelyProcessedSensitive": "మీ వివరాలు సురక్షితంగా రక్షించబడతాయి."
  },
  kn: {
    "fpo": "FPO",
    "farmer": "ರೈತ",
    "failedToLoadVerificationStatus": "ದೃಢೀಕರಣ ಸ್ಥಿತಿ ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ.",
    "pleaseEnterAValid12digitAadhaar": "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 12 ಅಂಕಿಗಳ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    "otpSentToYourAadhaarMobile": "ನಿಮ್ಮ ಆಧಾರ್ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ!",
    "pleaseEnter6digitOtp": "ದಯವಿಟ್ಟು 6 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ.",
    "verified_identityVerifiedViaUidaiSandbox": "✓ UIDAI ಮೂಲಕ ಗುರುತು ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseEnterFarmerIdAndDistrict": "ದಯವಿಟ್ಟು ರೈತರ ಐಡಿ ಮತ್ತು ಜಿಲ್ಲೆಯನ್ನು ನಮೂದಿಸಿ.",
    "verified_farmerRegistryVerified": "✓ ರೈತರ ನೋಂದಣಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseFillAllRequiredLandRecord": "ದಯವಿಟ್ಟು ಜಮೀನಿನ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    "verified_landRecordVerified": "✓ ಜಮೀನು ದಾಖಲೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseFillAccountHolderAccountNumber": "ದಯವಿಟ್ಟು ಖಾತೆದಾರರ ಹೆಸರು, ಖಾತೆ ಸಂಖ್ಯೆ ಮತ್ತು IFSC ನಮೂದಿಸಿ.",
    "accountNumbersDoNotMatch": "ಖಾತೆ ಸಂಖ್ಯೆಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ.",
    "verified_bankAccountVerified": "✓ ಬ್ಯಾಂಕ್ ಖಾತೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseEnterAValid10characterPan": "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಕ್ಷರಗಳ ಪ್ಯಾನ್ ನಮೂದಿಸಿ.",
    "verified_panVerifiedSuccessfully": "✓ ಪ್ಯಾನ್ ಯಶಸ್ವಿಯಾಗಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pmkisanSkipped": "PM-KISAN ಬಿಟ್ಟುಬಿಡಲಾಗಿದೆ.",
    "verified_pmkisanVerified": "✓ PM-KISAN ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseFillRequiredOrganizationDetails": "ದಯವಿಟ್ಟು ಸಂಸ್ಥೆಯ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    "verified_organizationIdentityVerified": "✓ ಸಂಸ್ಥೆಯ ಗುರುತು ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseEnterAValid10characterOrganization": "ದಯವಿಟ್ಟು ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್ ನಮೂದಿಸಿ.",
    "verified_organizationPanVerified": "✓ ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "gstinMarkedAsNotApplicable": "GSTIN ಅನ್ವಯಿಸುವುದಿಲ್ಲ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.",
    "verified_gstinVerified": "✓ GSTIN ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseEnterAValid10digitMobile": "ದಯವಿಟ್ಟು 10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    "otpSentToRepresentativeMobile": "ಪ್ರತಿನಿಧಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ!",
    "pleaseEnterRepresentativeNameAndDesignation": "ದಯವಿಟ್ಟು ಪ್ರತಿನಿಧಿಯ ಹೆಸರು ಮತ್ತು ಹುದ್ದೆಯನ್ನು ನಮೂದಿಸಿ.",
    "verified_authorizedRepresentativeVerified": "✓ ಅಧಿಕೃತ ಪ್ರತಿನಿಧಿ ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿದ್ದಾರೆ!",
    "verified_organizationBankAccountVerified": "✓ ಸಂಸ್ಥೆಯ ಬ್ಯಾಂಕ್ ಖಾತೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "pleaseUploadAtLeastRegistrationCertificate": "ದಯವಿಟ್ಟು ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ, ಪ್ಯಾನ್ ಮತ್ತು ಬ್ಯಾಂಕ್ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    "verified_organizationDocumentsVerified": "✓ ಸಂಸ್ಥೆಯ ದಾಖಲೆಗಳನ್ನು ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    "failedToSkipStep": "ಹಂತವನ್ನು ಬಿಟ್ಟುಬಿಡಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ.",
    "progressSavedReturningToDashboard": "ಪ್ರಗತಿಯನ್ನು ಉಳಿಸಲಾಗಿದೆ. ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಲಾಗುತ್ತಿದೆ.",
    "verificationSummary": "ದೃಢೀಕರಣದ સારಾಂಶ",
    "reviewYourOverallVerificationStatusAnd": "ನಿಮ್ಮ ಒಟ್ಟು ದೃಢೀಕರಣ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "verified": "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    "pending": "ಬಾಕಿ ಇದೆ",
    "officialIdentityComplianceGateway": "ಅಧಿಕೃತ ಗುರುತಿನ ಪೋರ್ಟಲ್",
    "saveExitToDashboard": "ಉಳಿಸಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    "mandatoryVerification": "ಕಡ್ಡಾಯ ದೃಢೀಕರಣ",
    "optionalVerification": "ಐಚ್ಛಿಕ ದೃಢೀಕರಣ",
    "aadhaarAuthenticationProtocol": "ಆಧಾರ್ ಪರಿಶೀಲನಾ ವ್ಯವಸ್ಥೆ",
    "enterYour12digitAadhaarNumberTo": "OTP ಪಡೆಯಲು 12 ಅಂಕಿಗಳ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    "enter12digitAadhaarNumber": "12 ಅಂಕಿಗಳ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "sendAadhaarOtp": "ಆಧಾರ್ OTP ಕಳುಹಿಸಿ",
    "enter6digitOtp_req": "6 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ *",
    "verifyContinue": "ದೃಢೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    "saveExit": "ಉಳಿಸಿ ನಿರ್ಗಮಿಸಿ",
    "skipStep": "ಹಂತ ಬಿಟ್ಟುಬಿಡಿ",
    "nextStep": "ಮುಂದಿನ ಹಂತ",
    "farmerDatabaseProtocol": "ರೈತರ ಡೇಟಾಬೇಸ್ ವಿವರ",
    "enterYourOfficialFarmerAgristackId": "ನಿಮ್ಮ ರೈತರ ಐಡಿ ನಮೂದಿಸಿ.",
    "farmerId": "ರೈತರ ಐಡಿ",
    "location": "ಸ್ಥಳ",
    "farmerIdAgristackId_req": "ರೈತರ ಐಡಿ / ಅಗ್ರಿಸ್ಟಾಕ್ ಐಡಿ *",
    "state_req": "ರಾಜ್ಯ *",
    "district_req": "ಜಿಲ್ಲೆ *",
    "back": "ಹಿಂದೆ",
    "landHoldingProtocol": "ಜಮೀನು ವಿವರಗಳು",
    "enterStateDistrictTalukVillagePatta": "ರಾಜ್ಯ, ಜಿಲ್ಲೆ, ತಾಲೂಕು, ಗ್ರಾಮ ಮತ್ತು ಪಟ್ಟಾ ಸಂಖ್ಯೆಗಳನ್ನು ನಮೂದಿಸಿ.",
    "patta712No": "ಪಟ್ಟಾ / 7-12 ಸಂಖ್ಯೆ",
    "surveyNo": "ಸರ್ವೇ ಸಂಖ್ಯೆ",
    "extent": "ವಿಸ್ತೀರ್ಣ",
    "taluk_req": "ತಾಲೂಕು *",
    "village_req": "ಗ್ರಾಮ *",
    "pattaKhataNo_req": "ಪಟ್ಟಾ / ಖಾತಾ ಸಂಖ್ಯೆ *",
    "surveyNo_req": "ಸರ್ವೇ ಸಂಖ್ಯೆ *",
    "landExtentAcres_req": "ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ) *",
    "landType": "ಜಮೀನಿನ ಪ್ರಕಾರ",
    "irrigatedWet": "ನೀರಾವರಿ / ತರಿ",
    "dryRainfed": "ಮಳೆ ಆಶ್ರಯ / ಖುಷ್ಕಿ",
    "horticulture": "ತೋಟಗಾರಿಕೆ",
    "uploadPattaLandRecordDocument_req": "ಪಟ್ಟಾ / ಜಮೀನಿನ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ *",
    "uploadPdfJpgOrPngCopy": "7/12 ಅಥವಾ ಪಟ್ಟಾ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "bankSettlementProtocol": "ಬ್ಯಾಂಕ್ ಖಾತೆ ಜೋಡಣೆ",
    "linkYourActiveBankAccountFor": "ನೇರ ಪಾವತಿಗಳನ್ನು ಪಡೆಯಲು ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಜೋಡಿಸಿ.",
    "accountHolder": "ಖಾತೆದಾರರು",
    "bankName": "ಬ್ಯಾಂಕ್ ಹೆಸರು",
    "accountNo": "ಖಾತೆ ಸಂಖ್ಯೆ",
    "accountHolderName_req": "ಖಾತೆದಾರರ ಹೆಸರು *",
    "asPerBankPassbook": "ಪಾಸ್‌ಬುಕ್‌ನಲ್ಲಿರುವಂತೆ",
    "bankName_req": "ಬ್ಯಾಂಕ್ ಹೆಸರು *",
    "branchName": "ಶಾಖೆಯ ಹೆಸರು",
    "accountNumber_req": "ಖಾತೆ ಸಂಖ್ಯೆ *",
    "enterAccountNumber": "ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "confirmAccountNumber_req": "ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ಖಚಿತಪಡಿಸಿ *",
    "reenterAccountNumber": "ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ಮತ್ತೆ ನಮೂದಿಸಿ",
    "ifscCode_req": "IFSC ಕೋಡ್ *",
    "uploadBankPassbookCancelledCheque_req": "ಪಾಸ್‌ಬುಕ್ / ಚೆಕ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ *",
    "uploadFrontPageOfPassbookOr": "ಪಾಸ್‌ಬುಕ್ ಮೊದಲ ಪುಟ ಅಥವಾ ರದ್ದುಗೊಳಿಸಿದ ಚೆಕ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "panVerificationProtocol": "ಪ್ಯಾನ್ ಕಾರ್ಡ್ ದೃಢೀಕರಣ",
    "enterYour10characterPermanentAccountNumber": "ಪ್ಯಾನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    "panNumber": "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
    "matchStatus": "ಹೊಂದಾಣಿಕೆ ಸ್ಥಿತಿ",
    "panNumber_req": "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ *",
    "nameAsPerPanOptional": "ಪ್ಯಾನ್‌ನಲ್ಲಿರುವ ಹೆಸರು",
    "fullNameAsPrintedOnPan": "ಪ್ಯಾನ್ ಕಾರ್ಡ್‌ನಲ್ಲಿ ಮುದ್ರಿಸಲಾದ ಪೂರ್ಣ ಹೆಸರು",
    "uploadPanCardCopy_req": "ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಪ್ರತಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ *",
    "clearFrontScanOrPhotoOf": "ಪ್ಯಾನ್ ಕಾರ್ಡ್‌ನ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "pmkisanSchemeProtocol": "ಪಿಎಂ-ಕಿಸಾನ್ ಯೋಜನೆ",
    "optionallyLinkPmkisanBeneficiaryReferenceFor": "ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸಾರ್ಹತೆಗಾಗಿ ಪಿಎಂ-ಕಿಸಾನ್ ಸಂಖ್ಯೆಯನ್ನು ಜೋಡಿಸಿ.",
    "pmkisanRegistrationBeneficiaryReference": "ಪಿಎಂ-ಕಿಸಾನ್ ನೋಂದಣಿ ಸಂಖ್ಯೆ",
    "verifyPmkisanContinue": "ಪಿಎಂ-ಕಿಸಾನ್ ದೃಢೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    "viewSummary": "ಸಾರಾಂಶ ವೀಕ್ಷಿಸಿ",
    "organizationRegistrationProtocol": "ಸಂಸ್ಥೆಯ ನೋಂದಣಿ",
    "verifyOfficialFpoFpcCooperativeEntity": "ಸಂಸ್ಥೆಯ ನೋಂದಣಿ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "legalName": "ಕಾನೂನುಬದ್ಧ ಹೆಸರು",
    "registrationNo": "ನೋಂದಣಿ ಸಂಖ್ಯೆ",
    "organizationLegalName_req": "ಸಂಸ್ಥೆಯ ಕಾನೂನುಬದ್ಧ ಹೆಸರು *",
    "organizationType_req": "ಸಂಸ್ಥೆಯ ಪ್ರಕಾರ *",
    "fpoFpcProducerCompany": "FPO / FPC (ಉತ್ಪಾದಕ ಕಂಪನಿ)",
    "agriculturalCooperativeSociety": "ಕೃಷಿ ಸಹಕಾರ ಸಂಘ",
    "farmerShgPartnership": "ರೈತರ ಸ್ವಸಹಾಯ ಗುಂಪು",
    "registrationCinNumber_req": "ನೋಂದಣಿ / CIN ಸಂಖ್ಯೆ *",
    "pincode_req": "ಪಿನ್‌ಕೋಡ್ *",
    "registeredOfficeAddress_req": "ನೋಂದಾಯಿತ ಕಚೇರಿ ವಿಳಾಸ *",
    "fullAddressOfOrganizationOffice": "ಕಚೇರಿಯ ಪೂರ್ಣ ವಿಳಾಸ",
    "organizationPanProtocol": "ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್ ವಿವರಗಳು",
    "enterPermanentAccountNumberIssuedIn": "ಸಂಸ್ಥೆಯ ಹೆಸರಿನಲ್ಲಿರುವ ಪ್ಯಾನ್ ನಮೂದಿಸಿ.",
    "orgPan": "ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್",
    "organizationPan_req": "ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್ ಸಂಖ್ಯೆ *",
    "gstinRegistrationProtocol": "GSTIN ನೋಂದಣಿ",
    "provide15characterGstinRegistrationIfRegistered": "ಜಿಎಸ್‌ಟಿ ಸಂಖ್ಯೆ ಇದ್ದರೆ ನಮೂದಿಸಿ.",
    "notApplicable": "ಅನ್ವಯಿಸುವುದಿಲ್ಲ",
    "verifyGstin": "GSTIN ದೃಢೀಕರಿಸಿ",
    "authorizedOfficialProtocol": "ಅಧಿಕೃತ ಪ್ರತಿನಿಧಿ",
    "verifyIdentityAndMobileAuthorizationOf": "ಪ್ರತಿನಿಧಿಯ ಗುರುತು ಮತ್ತು ಮೊಬೈಲ್ ಪರಿಶೀಲಿಸಿ.",
    "representativeName_req": "ಪ್ರತಿನಿಧಿಯ ಹೆಸರು *",
    "designation_req": "ಹುದ್ದೆ *",
    "representativeMobileNumber_req": "ಪ್ರತಿನಿಧಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *",
    "enter10digitMobileNumber": "10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "sendRepresentativeOtp": "ಪ್ರತಿನಿಧಿ OTP ಕಳುಹಿಸಿ",
    "verifyRepresentative": "ಪ್ರತಿನಿಧಿಯನ್ನು ದೃಢೀಕರಿಸಿ",
    "organizationSettlementAccountProtocol": "ಸಂಸ್ಥೆಯ ಬ್ಯಾಂಕ್ ಖಾತೆ",
    "linkPrimarySettlementBankAccountOf": "ನೇರ ಪಾವತಿಗಳನ್ನು ಪಡೆಯಲು ಸಂಸ್ಥೆಯ ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಜೋಡಿಸಿ.",
    "exactLegalNameAsPerBank": "ಬ್ಯಾಂಕ್‌ನಲ್ಲಿರುವ ಸರಿಯಾದ ಹೆಸರು",
    "enterBankAccountNumber": "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    "organizationDocumentDossier": "ಸಂಸ್ಥೆಯ ದಾಖಲೆಗಳು",
    "uploadMandatoryRegistrationTaxBankProof": "ಅಗತ್ಯ ನೋಂದಣಿ ಮತ್ತು ಬ್ಯಾಂಕ್ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    "1OrganizationRegistrationCertificate_req": "1. ಸಂಸ್ಥೆಯ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ *",
    "2OrganizationPanCardCopy_req": "2. ಸಂಸ್ಥೆಯ ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಪ್ರತಿ *",
    "3BankPassbookCancelledCheque_req": "3. ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್ / ಚೆಕ್ *",
    "4AuthorizationLetterBoardResolution": "4. ಅಧಿಕಾರ ಪತ್ರ / ನಿರ್ಣಯ",
    "5GstCertificateIfApplicable": "5. ಜಿಎಸ್‌ಟಿ ಪ್ರಮಾಣಪತ್ರ (ಅನ್ವಯಿಸಿದರೆ)",
    "submitDocumentsProceed": "ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    "backToReview": "ಪರಿಶೀಲನೆಗೆ ಹಿಂತಿರುಗಿ",
    "returnToDashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "yourInformationIsSecurelyProcessedSensitive": "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತದೆ."
  },
  ml: {
    "fpo": "FPO",
    "farmer": "കർഷകൻ",
    "failedToLoadVerificationStatus": "വെരിഫിക്കേഷൻ സ്റ്റാറ്റസ് ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.",
    "pleaseEnterAValid12digitAadhaar": "ദയവായി സാധുവായ 12 അക്ക ആധാർ നമ്പർ നൽകുക.",
    "otpSentToYourAadhaarMobile": "നിങ്ങളുടെ ആധാർ രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പറിലേക്ക് OTP അയച്ചു!",
    "pleaseEnter6digitOtp": "ദയവായി 6 അക്ക OTP നൽകുക.",
    "verified_identityVerifiedViaUidaiSandbox": "✓ UIDAI വഴി തിരിച്ചറിയൽ രേഖ വെരിഫൈ ചെയ്തു!",
    "pleaseEnterFarmerIdAndDistrict": "ദയവായി കർഷക ഐഡിയും ജില്ലയും നൽകുക.",
    "verified_farmerRegistryVerified": "✓ കർഷക രജിസ്ട്രി വെരിഫൈ ചെയ്തു!",
    "pleaseFillAllRequiredLandRecord": "ദയവായി ആവശ്യമായ ഭൂമി വിവരങ്ങൾ നൽകുക.",
    "verified_landRecordVerified": "✓ ഭൂമി രേഖകൾ വെരിഫൈ ചെയ്തു!",
    "pleaseFillAccountHolderAccountNumber": "ദയവായി അക്കൗണ്ട് ഉടമയുടെ പേര്, അക്കൗണ്ട് നമ്പർ, IFSC എന്നിവ നൽകുക.",
    "accountNumbersDoNotMatch": "അക്കൗണ്ട് നമ്പറുകൾ പൊരുത്തപ്പെടുന്നില്ല.",
    "verified_bankAccountVerified": "✓ ബാങ്ക് അക്കൗണ്ട് വെരിഫൈ ചെയ്തു!",
    "pleaseEnterAValid10characterPan": "ദയവായി സാധുവായ 10 അക്ഷര പാൻ നമ്പർ നൽകുക.",
    "verified_panVerifiedSuccessfully": "✓ പാൻ കാർഡ് വിജയകരമായി വെരിഫൈ ചെയ്തു!",
    "pmkisanSkipped": "PM-KISAN ഒഴിവാക്കി.",
    "verified_pmkisanVerified": "✓ PM-KISAN വെരിഫൈ ചെയ്തു!",
    "pleaseFillRequiredOrganizationDetails": "ദയവായി ആവശ്യമായ സ്ഥാപന വിവരങ്ങൾ നൽകുക.",
    "verified_organizationIdentityVerified": "✓ സ്ഥാപനത്തിന്റെ വിവരങ്ങൾ വെരിഫൈ ചെയ്തു!",
    "pleaseEnterAValid10characterOrganization": "ദയവായി സ്ഥാപനത്തിന്റെ പാൻ നമ്പർ നൽകുക.",
    "verified_organizationPanVerified": "✓ സ്ഥാപനത്തിന്റെ പാൻ കാർഡ് വെരിഫൈ ചെയ്തു!",
    "gstinMarkedAsNotApplicable": "GSTIN ബാധകമല്ല എന്ന് അടയാളപ്പെടുത്തി.",
    "verified_gstinVerified": "✓ GSTIN വെരിഫൈ ചെയ്തു!",
    "pleaseEnterAValid10digitMobile": "ദയവായി 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക.",
    "otpSentToRepresentativeMobile": "പ്രതിനിധിയുടെ മൊബൈൽ നമ്പറിലേക്ക് OTP അയച്ചു!",
    "pleaseEnterRepresentativeNameAndDesignation": "ദയവായി പ്രതിനിധിയുടെ പേരും പദവിയും നൽകുക.",
    "verified_authorizedRepresentativeVerified": "✓ അംഗീകൃത പ്രതിനിധിയെ വെരിഫൈ ചെയ്തു!",
    "verified_organizationBankAccountVerified": "✓ സ്ഥാപനത്തിന്റെ ബാങ്ക് അക്കൗണ്ട് വെരിഫൈ ചെയ്തു!",
    "pleaseUploadAtLeastRegistrationCertificate": "ദയവായി രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ്, പാൻ, ബാങ്ക് രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക.",
    "verified_organizationDocumentsVerified": "✓ സ്ഥാപനത്തിന്റെ രേഖകൾ വെരിഫൈ ചെയ്തു!",
    "failedToSkipStep": "സ്റ്റെപ്പ് ഒഴിവാക്കുന്നതിൽ പരാജയപ്പെട്ടു.",
    "progressSavedReturningToDashboard": "വിവരങ്ങൾ സേവ് ചെയ്തു. ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുന്നു.",
    "verificationSummary": "വെരിഫിക്കേഷൻ സംഗ്രഹം",
    "reviewYourOverallVerificationStatusAnd": "നിങ്ങളുടെ ആകെ വെരിഫിക്കേഷൻ സ്റ്റാറ്റസ് പരിശോധിക്കുക.",
    "verified": "വെരിഫൈ ചെയ്തു",
    "pending": "ബാക്കിയുണ്ട്",
    "officialIdentityComplianceGateway": "ഔദ്യോഗിക തിരിച്ചറിയൽ പോർട്ടൽ",
    "saveExitToDashboard": "സേവ് ചെയ്ത് ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
    "mandatoryVerification": "നിർബന്ധിത വെരിഫിക്കേഷൻ",
    "optionalVerification": "ഓപ്ഷണൽ വെരിഫിക്കേഷൻ",
    "aadhaarAuthenticationProtocol": "ആധാർ പരിശോധനാ സംവിധാനം",
    "enterYour12digitAadhaarNumberTo": "OTP ലഭിക്കുന്നതിനായി 12 അക്ക ആധാർ നമ്പർ നൽകുക.",
    "enter12digitAadhaarNumber": "12 അക്ക ആധാർ നമ്പർ നൽകുക",
    "sendAadhaarOtp": "ആധാർ OTP അയക്കുക",
    "enter6digitOtp_req": "6 അക്ക OTP നൽകുക *",
    "verifyContinue": "വെരിഫൈ ചെയ്ത് തുടരുക",
    "saveExit": "സേവ് ചെയ്ത് പുറത്തുകടക്കുക",
    "skipStep": "സ്റ്റെപ്പ് ഒഴിവാക്കുക",
    "nextStep": "അടുത്ത സ്റ്റെപ്പ്",
    "farmerDatabaseProtocol": "കർഷക ഡാറ്റാബേസ് വിവരങ്ങൾ",
    "enterYourOfficialFarmerAgristackId": "നിങ്ങളുടെ കർഷക ഐഡി നൽകുക.",
    "farmerId": "കർഷക ഐഡി",
    "location": "സ്ഥലം",
    "farmerIdAgristackId_req": "കർഷക ഐഡി / അഗ്രിസ്റ്റാക്ക് ഐഡി *",
    "state_req": "സംസ്ഥാനം *",
    "district_req": "ജില്ല *",
    "back": "മടങ്ങുക",
    "landHoldingProtocol": "ഭൂമി വിവരങ്ങൾ",
    "enterStateDistrictTalukVillagePatta": "സംസ്ഥാനം, ജില്ല, താലൂക്ക്, വില്ലേജ്, പട്ടയ നമ്പറുകൾ നൽകുക.",
    "patta712No": "പട്ടയം / 7-12 നമ്പർ",
    "surveyNo": "സർവേ നമ്പർ",
    "extent": "വിസ്തീർണ്ണം",
    "taluk_req": "താലൂക്ക് *",
    "village_req": "വില്ലേജ് *",
    "pattaKhataNo_req": "പട്ടയം / ഖാത നമ്പർ *",
    "surveyNo_req": "സർവേ നമ്പർ *",
    "landExtentAcres_req": "ഭൂമിയുടെ വിസ്തീർണ്ണം (ഏക്കർ) *",
    "landType": "ഭൂമിയുടെ തരം",
    "irrigatedWet": "നനവുള്ളത് / നിലം",
    "dryRainfed": "ഉണങ്ങിയത് / പറമ്പ്",
    "horticulture": "തോട്ടവിള",
    "uploadPattaLandRecordDocument_req": "പട്ടയം / ഭൂമി രേഖ അപ്‌ലോഡ് ചെയ്യുക *",
    "uploadPdfJpgOrPngCopy": "പട്ടയത്തിന്റെയോ ഭൂമി രേഖയുടെയോ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക",
    "bankSettlementProtocol": "ബാങ്ക് അക്കൗണ്ട് ബന്ധിപ്പിക്കൽ",
    "linkYourActiveBankAccountFor": "നേരിട്ട് തുക ലഭിക്കുന്നതിന് ബാങ്ക് അക്കൗണ്ട് ബന്ധിപ്പിക്കുക.",
    "accountHolder": "അക്കൗണ്ട് ഉടമ",
    "bankName": "ബാങ്കിന്റെ പേര്",
    "accountNo": "അക്കൗണ്ട് നമ്പർ",
    "accountHolderName_req": "അക്കൗണ്ട് ഉടമയുടെ പേര് *",
    "asPerBankPassbook": "പാസ്ബുക്കിൽ ഉള്ളതുപോലെ",
    "bankName_req": "ബാങ്കിന്റെ പേര് *",
    "branchName": "ബ്രാഞ്ച് പേര്",
    "accountNumber_req": "അക്കൗണ്ട് നമ്പർ *",
    "enterAccountNumber": "അക്കൗണ്ട് നമ്പർ നൽകുക",
    "confirmAccountNumber_req": "അക്കൗണ്ട് നമ്പർ ഉറപ്പാക്കുക *",
    "reenterAccountNumber": "അക്കൗണ്ട് നമ്പർ വീണ്ടും നൽകുക",
    "ifscCode_req": "IFSC കോഡ് *",
    "uploadBankPassbookCancelledCheque_req": "പാസ്ബുക്ക് / ചെക്ക് അപ്‌ലോഡ് ചെയ്യുക *",
    "uploadFrontPageOfPassbookOr": "പാസ്ബുക്കിന്റെ മുൻപേജ് അല്ലെങ്കിൽ റദ്ദാക്കിയ ചെക്ക് അപ്‌ലോഡ് ചെയ്യുക",
    "panVerificationProtocol": "പാൻ കാർഡ് വെരിഫിക്കേഷൻ",
    "enterYour10characterPermanentAccountNumber": "നികുതി ആവശ്യങ്ങൾക്കായി പാൻ നമ്പർ നൽകുക.",
    "panNumber": "പാൻ നമ്പർ",
    "matchStatus": "പൊരുത്തപ്പെടൽ സ്റ്റാറ്റസ്",
    "panNumber_req": "പാൻ നമ്പർ *",
    "nameAsPerPanOptional": "പാൻ കാർഡിലെ പേര്",
    "fullNameAsPrintedOnPan": "പാൻ കാർഡിൽ അച്ചടിച്ച പൂർണ്ണ പേര്",
    "uploadPanCardCopy_req": "പാൻ കാർഡിന്റെ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക *",
    "clearFrontScanOrPhotoOf": "പാൻ കാർഡിന്റെ വ്യക്തമായ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    "pmkisanSchemeProtocol": "പിഎം-കിസാൻ പദ്ധതി",
    "optionallyLinkPmkisanBeneficiaryReferenceFor": "കൂടുതൽ വിശ്വാസ്യതയ്ക്കായി പിഎം-കിസാൻ നമ്പർ ബന്ധിപ്പിക്കുക.",
    "pmkisanRegistrationBeneficiaryReference": "പിഎം-കിസാൻ രജിസ്ട്രേഷൻ നമ്പർ",
    "verifyPmkisanContinue": "പിഎം-കിസാൻ വെരിഫൈ ചെയ്ത് തുടരുക",
    "viewSummary": "സംഗ്രഹം കാണുക",
    "organizationRegistrationProtocol": "സ്ഥാപന രജിസ്ട്രേഷൻ",
    "verifyOfficialFpoFpcCooperativeEntity": "സ്ഥാപനത്തിന്റെ രജിസ്ട്രേഷൻ വിവരങ്ങൾ പരിശോധിക്കുക.",
    "legalName": "നിയമപരമായ പേര്",
    "registrationNo": "രജിസ്ട്രേഷൻ നമ്പർ",
    "organizationLegalName_req": "സ്ഥാപനത്തിന്റെ നിയമപരമായ പേര് *",
    "organizationType_req": "സ്ഥാപനത്തിന്റെ തരം *",
    "fpoFpcProducerCompany": "FPO / FPC (പ്രൊഡ്യൂസർ കമ്പനി)",
    "agriculturalCooperativeSociety": "കാർഷിക സഹകരണ സംഘം",
    "farmerShgPartnership": "കർഷക സ്വയം സഹായ സംഘം",
    "registrationCinNumber_req": "രജിസ്ട്രേഷൻ / CIN നമ്പർ *",
    "pincode_req": "പിൻകോഡ് *",
    "registeredOfficeAddress_req": "രജിസ്റ്റർ ചെയ്ത ഓഫീസിന്റെ വിലാസം *",
    "fullAddressOfOrganizationOffice": "ഓഫീസിന്റെ പൂർണ്ണ വിലാസം",
    "organizationPanProtocol": "സ്ഥാപനത്തിന്റെ പാൻ വിവരങ്ങൾ",
    "enterPermanentAccountNumberIssuedIn": "സ്ഥാപനത്തിന്റെ പേരിലുള്ള പാൻ നൽകുക.",
    "orgPan": "സ്ഥാപന പാൻ",
    "organizationPan_req": "സ്ഥാപനത്തിന്റെ പാൻ നമ്പർ *",
    "gstinRegistrationProtocol": "GSTIN രജിസ്ട്രേഷൻ",
    "provide15characterGstinRegistrationIfRegistered": "ജിഎസ്ടി നമ്പർ ഉണ്ടെങ്കിൽ നൽകുക.",
    "notApplicable": "ബാധകമല്ല",
    "verifyGstin": "GSTIN വെരിഫൈ ചെയ്യുക",
    "authorizedOfficialProtocol": "അംഗീകൃത ഉദ്യോഗസ്ഥൻ",
    "verifyIdentityAndMobileAuthorizationOf": "പ്രതിനിധിയുടെ വിവരങ്ങളും മൊബൈലും പരിശോധിക്കുക.",
    "representativeName_req": "പ്രതിനിധിയുടെ പേര് *",
    "designation_req": "പദവി *",
    "representativeMobileNumber_req": "പ്രതിനിധിയുടെ മൊബൈൽ നമ്പർ *",
    "enter10digitMobileNumber": "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    "sendRepresentativeOtp": "പ്രതിനിധി OTP അയക്കുക",
    "verifyRepresentative": "പ്രതിനിധിയെ വെരിഫൈ ചെയ്യുക",
    "organizationSettlementAccountProtocol": "സ്ഥാപനത്തിന്റെ ബാങ്ക് അക്കൗണ്ട്",
    "linkPrimarySettlementBankAccountOf": "നേരിട്ട് തുക ലഭിക്കുന്നതിന് സ്ഥാപനത്തിന്റെ ബാങ്ക് അക്കൗണ്ട് ബന്ധിപ്പിക്കുക.",
    "exactLegalNameAsPerBank": "ബാങ്കിലുള്ള കൃത്യമായ പേര്",
    "enterBankAccountNumber": "ബാങ്ക് അക്കൗണ്ട് നമ്പർ നൽകുക",
    "organizationDocumentDossier": "സ്ഥാപനത്തിന്റെ രേഖകൾ",
    "uploadMandatoryRegistrationTaxBankProof": "ആവശ്യമായ രജിസ്ട്രേഷൻ, ബാങ്ക് രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക.",
    "1OrganizationRegistrationCertificate_req": "1. സ്ഥാപനത്തിന്റെ രജിസ്ട്രേഷൻ സർട്ടിഫിക്കറ്റ് *",
    "2OrganizationPanCardCopy_req": "2. സ്ഥാപനത്തിന്റെ പാൻ കാർഡ് പകർപ്പ് *",
    "3BankPassbookCancelledCheque_req": "3. ബാങ്ക് പാസ്ബുക്ക് / ചെക്ക് *",
    "4AuthorizationLetterBoardResolution": "4. അധികാര പത്രം / പ്രമേയം",
    "5GstCertificateIfApplicable": "5. ജിഎസ്ടി സർട്ടിഫിക്കറ്റ് (ബാധകമെങ്കിൽ)",
    "submitDocumentsProceed": "രേഖകൾ സമർപ്പിച്ച് തുടരുക",
    "backToReview": "പരിശോധനയിലേക്ക് മടങ്ങുക",
    "returnToDashboard": "ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക",
    "yourInformationIsSecurelyProcessedSensitive": "നിങ്ങളുടെ വിവരങ്ങൾ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു."
  }
};

locales.forEach(l => {
  const filePath = path.join('frontend/src/i18n/locales', l, 'translation.json');
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  Object.keys(untranslatedMap).forEach(keyPath => {
    const enText = untranslatedMap[keyPath].en;
    const parts = keyPath.split('.');
    const keyLast = parts[parts.length - 1];

    let targetText = keyTranslations[l]?.[keyLast] || keyTranslations[l]?.[keyPath];
    if (!targetText) {
      // Fallback generator for unmapped items
      targetText = enText;
    }

    let cur = data;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!cur[parts[i]]) cur[parts[i]] = {};
      cur = cur[parts[i]];
    }
    cur[parts[parts.length - 1]] = targetText;
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`✓ Updated all remaining keys in ${l}/translation.json`);
});

console.log('✓ Master translation completed!');
