const en = { document: 'Upload document', imageHint: 'High quality JPG, PNG, or WEBP image up to 5MB', documentHint: 'PDF, JPG, JPEG, PNG or WEBP up to 5MB', uploadedDocument: 'Uploaded document', cloudinaryProtected: 'Cloudinary protected', fileTooLarge: 'File size exceeds {{size}} MB.', unsupportedType: 'Unsupported file type ({{type}}). Allowed: {{formats}}', pdfNotAllowed: 'PDF files are not allowed for image uploads.', progress: '{{progress}}% complete', chooseFile: 'Click to choose file', orDragDrop: 'or drag and drop' };
export default {
  'en-IN': { upload: en },
  'ta-IN': { upload: { ...en, document: 'ஆவணத்தைப் பதிவேற்று', uploadedDocument: 'பதிவேற்றிய ஆவணம்', cloudinaryProtected: 'Cloudinary பாதுகாக்கப்பட்டது', chooseFile: 'கோப்பைத் தேர்ந்தெடுக்க கிளிக் செய்யவும்', orDragDrop: 'அல்லது இழுத்து விடவும்', progress: '{{progress}}% முடிந்தது', fileTooLarge: 'கோப்பு அளவு {{size}} MB-ஐ மீறுகிறது.' } },
  'hi-IN': { upload: { ...en, document: 'दस्तावेज़ अपलोड करें', uploadedDocument: 'अपलोड किया गया दस्तावेज़', cloudinaryProtected: 'Cloudinary संरक्षित', chooseFile: 'फ़ाइल चुनने के लिए क्लिक करें', orDragDrop: 'या खींचकर छोड़ें', progress: '{{progress}}% पूर्ण', fileTooLarge: 'फ़ाइल का आकार {{size}} MB से अधिक है।' } },
  'te-IN': { upload: { ...en, document: 'పత్రాన్ని అప్‌లోడ్ చేయండి', uploadedDocument: 'అప్‌లోడ్ చేసిన పత్రం', cloudinaryProtected: 'Cloudinary రక్షితం', chooseFile: 'ఫైల్ ఎంచుకోవడానికి క్లిక్ చేయండి', orDragDrop: 'లేదా లాగి వదలండి', progress: '{{progress}}% పూర్తయింది' } },
  'kn-IN': { upload: { ...en, document: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', uploadedDocument: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆ', cloudinaryProtected: 'Cloudinary ರಕ್ಷಿತ', chooseFile: 'ಕಡತ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ', orDragDrop: 'ಅಥವಾ ಎಳೆದು ಬಿಡಿ', progress: '{{progress}}% ಪೂರ್ಣಗೊಂಡಿದೆ' } },
  'ml-IN': { upload: { ...en, document: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക', uploadedDocument: 'അപ്‌ലോഡ് ചെയ്ത രേഖ', cloudinaryProtected: 'Cloudinary സംരക്ഷിതം', chooseFile: 'ഫയൽ തിരഞ്ഞെടുക്കാൻ ക്ലിക്ക് ചെയ്യുക', orDragDrop: 'അല്ലെങ്കിൽ വലിച്ചിടുക', progress: '{{progress}}% പൂർത്തിയായി' } },
};
